'use strict';
const $ = (s) => document.querySelector(s);
const esc = (s) => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons = {
 nodes:'<circle cx="6" cy="7" r="3"/><circle cx="23" cy="7" r="3"/><circle cx="14.5" cy="24" r="3"/><path d="M9 7h11M7.5 10l5.5 11m8.5-11L16 21"/>',
 line:'<path d="M4 4v23h24M7 22l6-7 6 2 8-12"/><circle cx="13" cy="15" r="1"/><circle cx="19" cy="17" r="1"/>',
 network:'<circle cx="5" cy="8" r="2.5"/><circle cx="5" cy="23" r="2.5"/><circle cx="16" cy="5" r="2.5"/><circle cx="16" cy="16" r="2.5"/><circle cx="16" cy="27" r="2.5"/><circle cx="27" cy="16" r="2.5"/><path d="m7 7 6-2M7 9l7 6m-7 7 7-5m-7 7 7 3M18 6l7 8m-7 3h6m-6 9 7-8"/>',
 tune:'<path d="M4 7h10m6 0h8M4 16h3m6 0h15M4 25h14m6 0h4"/><circle cx="17" cy="7" r="3"/><circle cx="10" cy="16" r="3"/><circle cx="21" cy="25" r="3"/>',
 clusters:'<circle cx="8" cy="8" r="2"/><circle cx="14" cy="5" r="2"/><circle cx="12" cy="13" r="2"/><circle cx="6" cy="16" r="2"/><circle cx="24" cy="19" r="2"/><circle cx="20" cy="25" r="2"/><circle cx="27" cy="26" r="2"/>',
 reduce:'<path d="M4 5h24L19 16v10l-6 3V16Z"/><path d="M9 10h14"/>'
};
const badge = w => `<span class="badge-icon"><svg viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[w.icon]}</svg></span>`;
let current = COURSE[0];
let activeTab = 'explora';
let currentSection = 0;
const quizDrafts = {};
$('#week-grid').innerHTML = COURSE.map(w=>`<a class="week-card" href="#semana-${w.id}" style="--week-color:${w.color};--week-light:${w.light}"><div class="card-top">${badge(w)}<span class="week-counter">SEMANA 0${w.id}</span></div><h3>${w.short}</h3><p>${w.description}</p><div class="card-footer"><span>Conceptos · Ejercicios · Práctica</span><strong>Explorar</strong></div></a>`).join('');
function navigate(){
 const match = location.hash.match(/^#semana-([1-6])(?:\/(explora|ejercicio|practica|recursos)(?:\/([1-9]\d*))?)?$/);
 $('#home').hidden=!!match; $('#week-view').hidden=!match;
 if(match){current=COURSE[Number(match[1])-1];activeTab=match[2]||'explora';currentSection=Math.min(Number(match[3]||1)-1,LESSONS[current.id].length-1);
  $('#week-view').style.setProperty('--week-color',current.color);$('#week-view').style.setProperty('--week-light',current.light);
  $('#week-title').textContent=current.title;$('#week-description').textContent=current.description;$('#week-label').textContent=`SEMANA 0${current.id} · APRENDIZAJE AUTOMÁTICO I`;$('#breadcrumb-week').textContent=`Semana ${current.id}`;$('#large-badge').innerHTML=badge(current);
  $('#previous-week').hidden=current.id===1;$('#previous-week').href=`#semana-${current.id-1}`;$('#previous-week').textContent=`Semana ${current.id-1}`;
  $('#next-week').hidden=current.id===6;$('#next-week').href=`#semana-${current.id+1}`;$('#next-week').textContent=`Semana ${current.id+1}`;
  document.title=`Semana ${current.id}: ${current.title} · Aprendizaje Automático I`;renderTab();
 }else document.title='Aprendizaje Automático I · Aula de aprendizaje';
 window.scrollTo({top:0,behavior:'instant'});
}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{location.hash=`semana-${current.id}/${b.dataset.tab}`;}));
window.addEventListener('hashchange',navigate);
function renderTab(){
 document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('active',b.dataset.tab===activeTab);if(b.dataset.tab===activeTab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
 const host=$('#lesson-content');
 if(activeTab==='explora')host.innerHTML=renderExplore();
 if(activeTab==='ejercicio'){const e=current.exercise;host.innerHTML=`<div class="lesson-layout"><article class="panel"><p class="micro-label">EJEMPLO PASO A PASO</p><h2>${e.title}</h2><p>${e.intro}</p>${e.steps.map(([t,p],i)=>`<div class="step"><span class="step-number">${i+1}</span><div><h3>${t}</h3><p>${p}</p></div></div>`).join('')}${CourseVisuals.section(current.id,"ejercicio")}<h3>Llévalo a Python</h3><p class="small">Fragmento de referencia para trabajar en un cuaderno. Requiere preparar los datos y las variables indicadas; no se ejecuta en esta página.</p><pre><code>${esc(e.code)}</code></pre></article><aside><section class="panel"><p class="micro-label">PIENSA UN PASO MÁS</p><h2>Antes de ver la respuesta</h2><p>${e.challenge}</p><details><summary>Ver orientación</summary><p>${e.solution}</p></details></section><div class="callout">Prueba el laboratorio de esta semana y comprueba tus decisiones con la autoevaluación.</div></aside></div>`;}
 if(activeTab==='recursos')host.innerHTML=`<div class="panel"><p class="micro-label">MATERIALES DEL CURSO</p><h2>Continúa trabajando con los cuadernos</h2><p>Descarga los archivos de esta semana. Abre los cuadernos <b>.ipynb</b> en Jupyter o Google Colab y carga los datos que cada actividad solicite. Los laboratorios de la pestaña Practica funcionan directamente en esta página.</p><p class="small">Selección de los materiales proporcionados por el docente. Las soluciones de evaluaciones no se incluyen.</p></div><div class="resource-list">${current.resources.map(([file,title,desc])=>`<article class="panel resource"><span class="resource-type">${file.endsWith('.csv')?'DATOS · CSV':file.endsWith('.ipynb')?'CUADERNO · PYTHON':'GUÍA · TEXTO'}</span><h3>${title}</h3><p>${desc}</p><a href="materiales/semana_${current.id}/${encodeURIComponent(file)}" download>Descargar ${file.endsWith('.csv')?'datos':file.endsWith('.ipynb')?'cuaderno':'archivo'}</a></article>`).join('')}</div>`;
 if(activeTab==='practica'){
  host.innerHTML=`<section class="panel"><p class="micro-label">EXPERIMENTA</p><h2>${current.labTitle}</h2><p>${current.labIntro}</p><div id="lab"></div><p class="small">Simulación didáctica en el navegador. Los resultados describen únicamente los datos de este laboratorio.</p></section>${CourseVisuals.section(current.id,"practica")}<section class="panel quiz"><p class="micro-label">COMPRUEBA LO APRENDIDO</p><h2>Autoevaluación de la semana ${current.id}</h2><p>Responde las tres preguntas y revisa la explicación de cada respuesta. Puedes volver a intentarlo.</p><form id="quiz-form">${current.questions.map((q,i)=>`<fieldset><legend>${i+1}. ${q.q}</legend>${q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"><span>${o}</span></label>`).join('')}<div id="feedback-${i}" class="feedback" aria-live="polite"></div></fieldset>`).join('')}<button type="submit" class="primary">Comprobar respuestas</button><p id="quiz-summary" class="feedback quiz-summary" role="status"></p></form><p class="small">Actividad de autoaprendizaje: no envía calificaciones al docente. Las respuestas se conservan solo mientras esta página permanezca abierta.</p></section>${current.id===6?projectChecklist():''}`;
  renderLab();
  if(current.id===2)NeuronRegression.mount(host);
  if(current.id===3)ClassifierLabs.mount(host);
  if(current.id===3)DigitLab.mount(host);
  if(current.id===3){
   const threshold=host.firstElementChild;
   threshold.id='threshold-simulator';
   const tree=host.querySelector('#tree-simulator'),knn=host.querySelector('#knn-simulator'),digits=host.querySelector('#digit-simulator');
   const guide=host.querySelector('.visual-support'),quiz=host.querySelector('.quiz');
   const activities=[tree,knn,threshold,digits];
   activities.forEach((section,i)=>{section.querySelector('h2').textContent=`${i+1}. ${section.querySelector('h2').textContent}`;host.append(section);});
   host.append(guide,quiz);
   const intro=document.createElement('nav');intro.className='panel';intro.setAttribute('aria-label','Ruta de prácticas de la semana 3');
   intro.innerHTML='<p class="micro-label">RUTA DE PRÁCTICA</p><h2>Cuatro actividades, paso a paso</h2><p>Sigue el orden de los temas: reglas del árbol, vecinos de KNN, decisiones por umbral y red neuronal. Después registra tus observaciones y completa la autoevaluación.</p><ol><li><a href="#tree-simulator">Árbol de decisión: reglas y complejidad</a></li><li><a href="#knn-simulator">KNN: distancias y votación</a></li><li><a href="#threshold-simulator">Umbral: probabilidades y errores</a></li><li><a href="#digit-simulator">Red neuronal: dígitos del 0 al 9</a></li></ol>';
   intro.querySelectorAll('a').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();host.querySelector(link.getAttribute('href')).scrollIntoView({behavior:'smooth',block:'start'});}));
   host.prepend(intro);
  }
  if(current.id===6)Week6Labs.mount(host);
  PracticeOrder(host,current.id);
  const draft=quizDrafts[current.id]||{};
  for(const [name,value]of Object.entries(draft)){const input=$(`#quiz-form input[name="${name}"][value="${value}"]`);if(input)input.checked=true;}
  $('#quiz-form').addEventListener('change',e=>{quizDrafts[current.id]??={};quizDrafts[current.id][e.target.name]=e.target.value;const f=$(`#feedback-${e.target.name.slice(1)}`);if(f){f.textContent='';f.className='feedback';}$('#quiz-summary').textContent='';});
  $('#quiz-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);let score=0,answered=0;current.questions.forEach((q,i)=>{const value=data.get(`q${i}`);const valid=value!==null;const correct=valid&&Number(value)===q.answer;answered+=valid?1:0;score+=correct?1:0;const feedback=$(`#feedback-${i}`);feedback.className=`feedback ${correct?'correct':'incorrect'}`;feedback.textContent=!valid?'Selecciona una respuesta para comprobar esta pregunta.':`${correct?'Correcto.':'Revisa tu respuesta.'} ${q.why}`;});$('#quiz-summary').textContent=answered<3?`Has respondido ${answered} de 3 preguntas. Completa las restantes.`:`Resultado: ${score} de 3 respuestas correctas. ${score===3?'Has comprendido los conceptos de esta autoevaluación.':'Revisa las explicaciones y vuelve a intentarlo.'}`;});
 }
 if(activeTab==='recursos')host.insertAdjacentHTML('beforeend',CourseReferences.render(current.id)+CourseVisuals.section(current.id,'recursos'));
 if(activeTab==='explora')host.insertAdjacentHTML('beforeend',`<details class="panel"><summary>Referencias de consulta de esta semana</summary>${CourseReferences.render(current.id)}</details>`);
}
function renderExplore(){
 const sections=LESSONS[current.id],s=sections[currentSection];
 const sectionUrl=i=>`#semana-${current.id}/explora/${i+1}`;
 return `<div class="topic-layout"><aside class="topic-sidebar"><nav class="panel topic-index" aria-label="Subsecciones de la semana ${current.id}"><p class="micro-label">CONTENIDO DE LA SEMANA</p><h2>${sections.length} temas, paso a paso</h2><ol>${sections.map((item,i)=>`<li><a href="${sectionUrl(i)}" ${i===currentSection?'aria-current="location"':''}><span class="topic-number">${current.id}.${i+1}</span><span>${esc(item.title)}</span></a></li>`).join('')}</ol></nav><details class="weekly-objectives"><summary>Objetivos de la semana</summary><ul>${current.objectives.map(o=>`<li>${esc(o)}</li>`).join('')}</ul></details></aside><div class="topic-reading"><article class="panel topic-article" aria-labelledby="topic-title"><div class="topic-meta"><p class="micro-label">SUBSECCIÓN ${current.id}.${currentSection+1}</p><span>${currentSection+1} de ${sections.length}</span></div><h2 id="topic-title">${esc(s.title)}</h2><p class="topic-goal"><strong>Qué aprenderás:</strong> ${esc(s.goal)}</p><section aria-labelledby="topic-explanation"><h3 id="topic-explanation">Comprende el concepto</h3>${s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</section><section class="topic-points" aria-labelledby="topic-keys"><h3 id="topic-keys">Puntos clave</h3><ul>${s.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul></section><section class="callout" aria-labelledby="topic-example"><h3 id="topic-example">Ejemplo aplicado</h3><p>${esc(s.example)}</p></section>${CourseVisuals.render(current.id,currentSection)}<section class="topic-check" aria-labelledby="topic-question"><p class="micro-label">PAUSA Y REFLEXIONA</p><h3 id="topic-question">${esc(s.question)}</h3><details><summary>Consultar respuesta orientativa</summary><p>${esc(s.answer)}</p></details></section><nav class="topic-navigation" aria-label="Navegación de subsecciones">${currentSection>0?`<a class="topic-back" href="${sectionUrl(currentSection-1)}">Tema anterior</a>`:'<span></span>'}${currentSection<sections.length-1?`<a class="primary topic-next" href="${sectionUrl(currentSection+1)}">Siguiente: ${current.id}.${currentSection+2}</a>`:`<a class="primary topic-next" href="#semana-${current.id}/ejercicio">Continuar con el ejercicio</a>`}</nav></article><details class="panel topic-reference"><summary>Referencia rápida de la semana</summary><div class="formula">${esc(current.formula).replace(/\n/g,'<br>')}</div><p>${esc(current.caution)}</p></details></div></div>`;
}
function projectChecklist(){return `<section class="panel"><p class="micro-label">INTEGRA LO APRENDIDO</p><h2>Guía para tu proyecto final</h2><p>Consulta el instructivo completo en Materiales. Usa esta lista como apoyo para organizar tu trabajo.</p>${['Definir MPG como objetivo y revisar la calidad de los datos.','Separar entrenamiento y prueba antes de aprender transformaciones.','Calcular información mutua en entrenamiento y justificar la característica seleccionada.','Entrenar la regresión y comparar con una referencia sencilla.','Reportar métricas en prueba e interpretar los residuos.','Documentar decisiones, resultados y limitaciones.'].map(t=>`<label class="checkline"><input type="checkbox"><span>${t}</span></label>`).join('')}<p class="small">Lista de apoyo temporal; no registra entregas ni sustituye el instructivo.</p></section>`;}
const fmt=(v,d=2)=>Number(v).toLocaleString('es-CR',{maximumFractionDigits:d,minimumFractionDigits:d});
const pct=(n,d)=>d===0?'No definida':`${fmt(n/d*100)} %`;
const metric=(label,value)=>`<div class="metric"><span>${label}</span><strong>${value}</strong></div>`;
const range=(id,label,min,max,value,step=1)=>`<label class="field" for="${id}"><span>${label}: <strong id="${id}-value">${value}</strong></span><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></label>`;
const number=(id,label,value)=>`<label class="field" for="${id}">${label}<input id="${id}" type="number" min="0" max="10000" step="1" value="${value}" required></label>`;
function renderLab(){
 const lab=$('#lab');
 if(current.lab==='confusion'){
  lab.innerHTML=`<div class="lab-grid"><div><div class="field-row">${number('vp','Verdaderos positivos (VP)',30)}${number('fp','Falsos positivos (FP)',10)}${number('fn','Falsos negativos (FN)',5)}${number('vn','Verdaderos negativos (VN)',55)}</div><p class="small">VP y FN corresponden a positivos reales; FP y VN, a negativos reales.</p></div><div class="result-box" id="lab-result" aria-live="polite"></div></div>`;
  const update=()=>{const inputs=['vp','fp','fn','vn'].map(id=>$('#'+id));if(inputs.some(i=>!i.validity.valid)){ $('#lab-result').innerHTML='<p>Ingresa números enteros entre 0 y 10 000 en los cuatro campos.</p>';return;}const [vp,fp,fn,vn]=inputs.map(i=>Number(i.value));$('#lab-result').innerHTML='<h3>Resultados del modelo</h3>'+metric('Mensajes evaluados',vp+fp+fn+vn)+metric('Exactitud',pct(vp+vn,vp+fp+fn+vn))+metric('Precisión',pct(vp,vp+fp))+metric('Recall',pct(vp,vp+fn))+metric('F1',pct(2*vp,2*vp+fp+fn))+'<p class="small">Si el denominador es cero, la métrica se muestra como no definida.</p>';};lab.addEventListener('input',update);update();
 }
 if(current.lab==='regression'){
  lab.innerHTML=`<div class="lab-grid"><div>${range('slope','Pendiente',0,8,2,.1)}${range('intercept','Intercepto',0,40,10,1)}<div class="result-box" id="lab-result" aria-live="polite"></div></div><div><div id="lab-chart"></div><p class="small">Puntos: valores observados. Recta: predicción del modelo.<br>x: inversión; y: unidades vendidas.</p></div></div>`;
  const pts=[[1,25],[2,27],[3,34],[4,35],[5,42]];const update=()=>{const m=Number($('#slope').value),b=Number($('#intercept').value);$('#slope-value').textContent=fmt(m,1);$('#intercept-value').textContent=b;const mae=pts.reduce((s,[x,y])=>s+Math.abs(y-(b+m*x)),0)/pts.length;$('#lab-result').innerHTML=metric('Tu modelo',`ŷ = ${b} + ${fmt(m,1)}x`)+metric('MAE',`${fmt(mae)} unidades`);$('#lab-chart').innerHTML=chart([{points:pts,color:'#007b70',dots:true},{points:[[0,b],[6,b+6*m]],color:current.color}],6,90,'Recta de regresión y observaciones');};lab.addEventListener('input',update);update();
 }
 if(current.lab==='threshold'){
  lab.innerHTML=`${range('threshold','Umbral',0,1,.5,.05)}<div class="lab-grid"><div class="table-wrap" id="prediction-table"></div><div class="result-box" id="lab-result" aria-live="polite"></div></div>`;
  const data=[[.2,0],[.45,1],[.65,0],[.9,1]];const update=()=>{const t=Number($('#threshold').value);$('#threshold-value').textContent=fmt(t);let vp=0,fp=0,fn=0,vn=0;const rows=data.map(([p,y],i)=>{const pred=p>=t?1:0;if(pred&&y)vp++;else if(pred&&!y)fp++;else if(!pred&&y)fn++;else vn++;return `<tr><td>${i+1}</td><td>${fmt(p)}</td><td>${y}</td><td>${pred}</td></tr>`;});$('#prediction-table').innerHTML=`<table><caption>1 = clase A; 0 = otra clase</caption><thead><tr><th>Fruta</th><th>p(A)</th><th>Real</th><th>Predicha</th></tr></thead><tbody>${rows.join('')}</tbody></table>`;$('#lab-result').innerHTML=metric('VP / FP / FN / VN',`${vp} / ${fp} / ${fn} / ${vn}`)+metric('Precisión',pct(vp,vp+fp))+metric('Recall',pct(vp,vp+fn))+metric('Exactitud',pct(vp+vn,4));};lab.addEventListener('input',update);update();
 }
 if(current.lab==='epochs'){
  lab.innerHTML=`<div class="lab-grid"><div>${range('epoch','Época',1,6,1)}<div class="result-box" id="lab-result" aria-live="polite"></div></div><div id="lab-chart"></div></div>`;
  const train=[.7,.52,.39,.29,.21,.16],val=[.74,.57,.48,.46,.51,.6];const update=()=>{const i=Number($('#epoch').value)-1;$('#epoch-value').textContent=i+1;$('#lab-result').innerHTML=metric('Pérdida de entrenamiento',fmt(train[i]))+metric('Pérdida de validación',fmt(val[i]))+`<p>${i<3?'Hasta esta época, ambas pérdidas disminuyen.':i===3?'Esta época tiene la menor pérdida de validación: 0,46.':'Validación empeora mientras entrenamiento mejora: señal de sobreajuste.'}</p>`;$('#lab-chart').innerHTML=chart([{points:train.map((v,i)=>[i+1,v]),color:'#007b70'},{points:val.map((v,i)=>[i+1,v]),color:'#aa6215'}],6,.8,'Pérdida por época',i+1)+'<p class="small">Verde: entrenamiento. Ocre: validación. Línea vertical: época seleccionada.</p>';};lab.addEventListener('input',update);update();
 }
 if(current.lab==='kmeans'){
  lab.innerHTML=`<div class="lab-grid"><div>${range('center-a','Centro A',0,11,1,.1)}${range('center-b','Centro B',0,11,8,.1)}<button class="primary" id="update-centers">Actualizar a las medias</button><p class="small">En caso de empate se asigna al grupo A. Si un grupo queda vacío, su centro se conserva.</p></div><div class="result-box" id="lab-result" aria-live="polite"></div></div>`;
  let nextA=1,nextB=8;const data=[1,2,3,8,9,10];const update=()=>{const a=Number($('#center-a').value),b=Number($('#center-b').value);$('#center-a-value').textContent=fmt(a,1);$('#center-b-value').textContent=fmt(b,1);const ga=data.filter(x=>Math.abs(x-a)<=Math.abs(x-b));const gb=data.filter(x=>Math.abs(x-a)>Math.abs(x-b));nextA=ga.length?ga.reduce((s,x)=>s+x,0)/ga.length:a;nextB=gb.length?gb.reduce((s,x)=>s+x,0)/gb.length:b;const inertia=ga.reduce((s,x)=>s+(x-a)**2,0)+gb.reduce((s,x)=>s+(x-b)**2,0);$('#lab-result').innerHTML=metric('Grupo A',ga.join(', ')||'Vacío')+metric('Grupo B',gb.join(', ')||'Vacío')+metric('Nueva media A',ga.length?fmt(nextA):'Sin puntos')+metric('Nueva media B',gb.length?fmt(nextB):'Sin puntos')+metric('Inercia actual',fmt(inertia))+`<p class="small">${!ga.length||!gb.length?'Hay un grupo vacío. Prueba separar los centros iniciales.':'Compara los centros actuales con las nuevas medias. Pulsa el botón para realizar una actualización.'}</p>`;};lab.addEventListener('input',update);$('#update-centers').addEventListener('click',()=>{$('#center-a').value=nextA.toFixed(1);$('#center-b').value=nextB.toFixed(1);update();});update();
 }
 if(current.lab==='pca'){
  lab.innerHTML=`<div class="lab-grid"><div>${range('components','Componentes conservados',1,4,2)}<div class="result-box" id="lab-result" aria-live="polite"></div></div><div id="lab-chart"></div></div>`;
  const ratios=[50,25,15,10];const update=()=>{const n=Number($('#components').value),sum=ratios.slice(0,n).reduce((a,b)=>a+b,0);$('#components-value').textContent=n;$('#lab-result').innerHTML=metric('Varianza conservada',sum+' %')+metric('Varianza descartada',(100-sum)+' %')+`<p>${sum>=90?'Alcanzas el objetivo de al menos 90 %. El mínimo suficiente es tres componentes.':'Todavía no alcanzas el objetivo del 90 %. Prueba conservar más componentes.'}</p>`;$('#lab-chart').innerHTML=`<svg viewBox="0 0 440 260" class="chart" role="img" aria-label="Varianza individual por componente. 50, 25, 15 y 10 por ciento.">${ratios.map((v,i)=>`<rect x="${45+i*98}" y="${205-v*3}" width="58" height="${v*3}" rx="4" fill="${i<n?current.color:'#cfd9e3'}"/><text x="${74+i*98}" y="${195-v*3}" text-anchor="middle">${v} %</text><text x="${74+i*98}" y="230" text-anchor="middle">CP ${i+1}</text>`).join('')}</svg><p class="small">Color: componentes conservados. Gris: descartados. Las barras muestran varianza individual, no acumulada.</p>`;};lab.addEventListener('input',update);update();
 }
}
function chart(series,xmax,ymax,title,marker){
 const px=x=>45+x/xmax*365,py=y=>220-y/ymax*190;
 return `<svg viewBox="0 0 450 265" class="chart" role="img" aria-label="${esc(title)}"><title>${esc(title)}</title>${[0,.25,.5,.75,1].map(f=>`<path d="M45 ${py(f*ymax)}H410" stroke="#e5ebf0"/><text x="36" y="${py(f*ymax)+4}" text-anchor="end">${fmt(f*ymax,ymax<1?2:0)}</text>`).join('')}<path d="M45 25V220H410" stroke="#a8b9c7" fill="none"/>${Array.from({length:7},(_,i)=>`<text x="${px(i)}" y="242" text-anchor="middle">${i}</text>`).join('')}${marker?`<path d="M${px(marker)} 25V220" stroke="#687c8c" stroke-dasharray="4 4"/>`:''}${series.map(s=>s.dots?s.points.map(([x,y])=>`<circle cx="${px(x)}" cy="${py(y)}" r="5" fill="${s.color}"/>`).join(''):`<polyline points="${s.points.map(([x,y])=>`${px(x)},${py(y)}`).join(' ')}" fill="none" stroke="${s.color}" stroke-width="3"/>`).join('')}</svg>`;
}
navigate();
