window.COURSE = [
  {
    id:1, title:'Fundamentos y métricas', short:'Fundamentos de aprendizaje automático', description:'Comprende cómo aprende un modelo y cómo evaluar sus predicciones.', color:'#08796e', light:'#e2f3ed', icon:'nodes',
    objectives:['Distinguir aprendizaje supervisado y no supervisado.','Separar entrenamiento, validación y prueba sin filtrar información.','Interpretar una matriz de confusión y calcular sus métricas.'],
    concepts:[
      ['Aprender a partir de ejemplos','Un modelo aprende patrones a partir de datos para realizar predicciones sobre casos nuevos. Las características (X) describen cada caso; la variable objetivo (y) es aquello que queremos predecir. Por ejemplo, usar área y ubicación para estimar el precio de una vivienda.'],
      ['Dos formas de aprender','En el aprendizaje supervisado existen respuestas conocidas: predecir un precio es regresión y predecir una categoría es clasificación. En el no supervisado no entregamos una respuesta objetivo: buscamos estructura, como segmentos de clientes.'],
      ['Un flujo de trabajo confiable','Define el problema, revisa los datos, separa los conjuntos, prepara las variables, entrena y evalúa. Aprende los parámetros del preprocesamiento solo con entrenamiento. Usa validación para elegir configuraciones y reserva prueba para la evaluación final.'],
      ['No todas las métricas responden lo mismo','La exactitud (accuracy) mide aciertos totales. La precisión responde qué proporción de los positivos predichos es correcta. La sensibilidad (recall) indica qué proporción de los positivos reales fue detectada. F1 combina precisión y recall mediante su media armónica.']
    ],
    caution:'Una exactitud alta puede ocultar un mal desempeño cuando una clase es mucho más frecuente. Define qué error cuesta más antes de elegir una métrica.',
    formula:'Exactitud = (VP + VN) / total\nPrecisión = VP / (VP + FP)\nRecall = VP / (VP + FN)\nF1 = 2VP / (2VP + FP + FN)',
    exercise:{title:'Clasificar mensajes no deseados',intro:'En 100 mensajes, el modelo identifica 30 correos no deseados correctamente (VP), marca 10 legítimos por error (FP), deja pasar 5 no deseados (FN) y reconoce 55 legítimos (VN). La clase positiva es «no deseado».',steps:[['Calcula la exactitud','(30 + 55) / 100 = 0,85. El modelo acierta en el 85 % de todos los mensajes.'],['Calcula precisión y recall','Precisión = 30 / 40 = 75 %. Recall = 30 / 35 ≈ 85,71 %. Detecta buena parte del correo no deseado, pero una de cada cuatro alertas es incorrecta.'],['Interpreta F1','F1 = 60 / 75 = 0,80. Es un balance entre precisión y recall, no un reemplazo del análisis del costo de cada error.']],code:'from sklearn.metrics import classification_report\n\n# y_test: etiquetas reales; y_pred: predicciones\nprint(classification_report(y_test, y_pred, zero_division=0))',challenge:'Si se vuelve más estricto el umbral para declarar un correo no deseado, ¿qué podría pasar con los falsos positivos y los falsos negativos?',solution:'Al elevar el umbral, normalmente se predicen menos positivos: pueden bajar los falsos positivos y aumentar los falsos negativos. Compruébalo con datos; el efecto exacto depende del modelo.'},
    labTitle:'Laboratorio de matriz de confusión',labIntro:'Modifica los conteos y observa qué métricas cambian. Prueba aumentar solo los falsos negativos.',lab:'confusion',
    questions:[{q:'¿Qué tarea corresponde a aprendizaje no supervisado?',options:['Predecir el precio de una casa.','Agrupar clientes por comportamientos similares.','Detectar correo no deseado con ejemplos etiquetados.'],answer:1,why:'El agrupamiento encuentra estructura sin utilizar una etiqueta objetivo conocida.'},{q:'Si aumenta FN y los demás conteos no cambian, ¿qué sucede con recall?',options:['Aumenta.','No cambia.','Disminuye.'],answer:2,why:'Recall = VP / (VP + FN). Al aumentar FN, aumenta el denominador.'},{q:'¿Cuándo debe ajustarse un escalador para evitar fuga de información?',options:['Solo con los datos de entrenamiento.','Con todos los datos antes de separarlos.','Solo con el conjunto de prueba.'],answer:0,why:'Los parámetros del escalador se aprenden en entrenamiento y después se aplican a validación y prueba.'}],
    resources:[['LEEME_CUADERNOS.md','Guía de ejecución','Orden de ejecución, datos y dependencias.'],['requirements.txt','Dependencias de Python','Versiones utilizadas para revisar los cuadernos.'],['1_fundamentos_practicos_ml.ipynb','Fundamentos prácticos','Teoría y flujo de trabajo con scikit-learn.'],['2_fundamentos_ml_aplicacion_practica.ipynb','Aplicación de los fundamentos','Ejemplos de preparación, entrenamiento y validación.'],['3_Metricas_Clasificacion_ML.ipynb','Métricas de clasificación','Matriz de confusión, precisión, recall y F1.']]
  },
  {
    id:2,title:'Regresión y predicción',short:'Regresión y predicción',description:'Modela relaciones numéricas y aprende a interpretar el error de tus predicciones.',color:'#2861a5',light:'#e8f0fc',icon:'line',
    objectives:['Interpretar pendiente e intercepto de un modelo lineal.','Calcular predicciones, residuos y error absoluto medio.','Evaluar regresión con datos que el modelo no ha visto.'],
    concepts:[['Una salida numérica','La regresión estima valores continuos, como ventas, consumo de combustible o precio. Una regresión lineal simple usa una característica; la múltiple combina varias.'],['Pendiente e intercepto','En ŷ = b₀ + b₁x, b₀ es la predicción cuando x = 0 y b₁ es el cambio esperado en la predicción por cada unidad adicional de x. Un coeficiente describe una asociación: por sí solo no demuestra causalidad.'],['Observar los residuos','El residuo es y − ŷ. Un patrón curvo en los residuos puede indicar que una recta no captura la relación. Una dispersión que crece con la predicción puede revelar variabilidad no constante.'],['Evaluar más allá de R²','MAE expresa el error absoluto medio en las unidades del objetivo. RMSE penaliza con más fuerza los errores grandes. R² compara con una predicción constante basada en la media del conjunto evaluado; puede ser negativo. Modelos con R² similar pueden tener patrones de error distintos.']],
    caution:'Evalúa en datos separados y compara contra una referencia sencilla. Evita extrapolar muy lejos del rango observado.',formula:'Predicción: ŷ = b₀ + b₁x\nResiduo: e = y − ŷ\nMAE = promedio(|y − ŷ|)',
    exercise:{title:'Estimar ventas a partir de publicidad',intro:'Ejemplo didáctico: x representa decenas de miles de colones en publicidad y y, unidades vendidas. Usa el modelo ŷ = 20 + 4x para los casos (2, 30), (4, 34) y (6, 47).',steps:[['Obtén las predicciones','Para x = 2, 4 y 6, las predicciones son 28, 36 y 44 unidades.'],['Calcula los residuos','30 − 28 = 2; 34 − 36 = −2; 47 − 44 = 3. Un residuo positivo indica que el modelo subestimó el valor observado.'],['Resume el error','MAE = (2 + 2 + 3) / 3 ≈ 2,33 unidades. Esto describe estos tres casos, no garantiza el mismo error en nuevos datos.']],code:'from sklearn.linear_model import LinearRegression\nfrom sklearn.metrics import mean_absolute_error, r2_score\n\nmodelo = LinearRegression().fit(X_train, y_train)\npred = modelo.predict(X_test)\nprint("MAE:", mean_absolute_error(y_test, pred))\nprint("R²:", r2_score(y_test, pred))',challenge:'Dos modelos tienen el mismo R². ¿Qué revisarías antes de elegir uno?',solution:'Compara MAE o RMSE en el mismo conjunto de validación, inspecciona residuos, identifica errores en segmentos relevantes y considera simplicidad y estabilidad.'},
    labTitle:'Ajusta tu recta',labIntro:'Cambia la pendiente y el intercepto para acercar la recta a los cinco puntos. El MAE se calcula sobre estos datos didácticos.',lab:'regression',
    questions:[{q:'En ŷ = 20 + 4x, ¿qué significa el 4?',options:['El cambio de 4 unidades en ŷ por cada unidad de x.','El error medio del modelo.','El número de variables de entrada.'],answer:0,why:'La pendiente describe el cambio esperado de la predicción cuando x aumenta una unidad.'},{q:'Si y = 47 y ŷ = 44, ¿cuál es el residuo y − ŷ?',options:['−3.','3.','91.'],answer:1,why:'47 − 44 = 3: el modelo subestimó el valor observado.'},{q:'¿Qué significa un R² negativo en prueba?',options:['Que el modelo siempre predice números negativos.','Que no se puede calcular MAE.','Que su error cuadrático supera al de usar la media del objetivo de ese conjunto.'],answer:2,why:'R² = 1 − SSE/SST. Es negativo cuando SSE supera a SST.'}],
    resources:[['LEEME_CUADERNOS.md','Guía de ejecución','Orden de ejecución, datos y dependencias.'],['requirements.txt','Dependencias de Python','Versiones utilizadas para revisar los cuadernos.'],['1_regresion_lineal_simple.ipynb','Regresión lineal simple','Ecuación y aplicación de un modelo lineal.'],['2_Análisis_residuos.ipynb','Análisis de residuos','Inspección de errores y comparación de modelos.'],['trabajo_grupal_I_parte_2_Regresion_Lineal_Multiple.ipynb','Práctica: predicción de ventas','Regresión múltiple con inversión publicitaria.'],['Advertising.csv','Datos de publicidad','Archivo para el ejercicio de regresión múltiple.']]
  },
  {
    id:3,title:'Clasificación y redes neuronales',short:'Clasificación y redes neuronales',description:'Asigna categorías, compara clasificadores y comprende el funcionamiento de una red neuronal.',color:'#754ab0',light:'#f0eafb',icon:'network',
    objectives:['Distinguir probabilidad, puntuación y clase predicha.','Comprender capas, activaciones y aprendizaje de pesos.','Comparar clasificadores con una evaluación común.'],
    concepts:[['Predecir una categoría','Un clasificador aprende a asignar etiquetas: tipo de fruta, especie de flor o clase de imagen. Árboles, vecinos cercanos y redes neuronales resuelven este tipo de tarea con diferentes supuestos.'],['De la puntuación a la decisión','En clasificación binaria se puede comparar la probabilidad estimada de la clase positiva con un umbral. Cambiarlo cambia las decisiones y los tipos de error, aunque el modelo entrenado sea el mismo. Una probabilidad estimada no es una certeza.'],['Dentro de una red neuronal','Cada neurona combina entradas y pesos, añade un sesgo y aplica una función de activación. Durante el entrenamiento se ajustan los pesos para reducir una función de pérdida. Las capas ocultas permiten aprender relaciones no lineales.'],['Una comparación justa','Usa la misma partición de datos y las mismas métricas para todos los modelos. Ajusta las transformaciones en entrenamiento y conserva intacta la prueba. En imágenes, los ejemplos de entrenamiento y prueba deben representar casos independientes.']],
    caution:'Una red más grande no es automáticamente mejor. Compara con modelos sencillos y analiza los errores por clase.',formula:'Neurona: z = w₁x₁ + w₂x₂ + … + b\nSalida: a = activación(z)\nDecisión binaria: positiva si p ≥ umbral',
    exercise:{title:'Decidir si una fruta es de clase A',intro:'Cuatro frutas tienen probabilidades estimadas de pertenecer a la clase A: 0,20; 0,45; 0,65 y 0,90. Sus etiquetas reales son 0, 1, 0 y 1. Aquí 1 significa clase A.',steps:[['Aplica el umbral 0,50','Las predicciones son 0, 0, 1 y 1. Se obtiene VP = 1, FP = 1, FN = 1 y VN = 1. Exactitud = 50 %.'],['Cambia el umbral a 0,70','Las predicciones son 0, 0, 0 y 1. Ahora VP = 1, FP = 0, FN = 1 y VN = 2. La precisión sube al 100 %, pero recall sigue en 50 %.'],['Interpreta el resultado','En estos cuatro casos, subir el umbral eliminó un falso positivo. Un conjunto tan pequeño sirve para comprender la regla, no para elegir un umbral para producción.']],code:'from sklearn.neural_network import MLPClassifier\nfrom sklearn.pipeline import make_pipeline\nfrom sklearn.preprocessing import StandardScaler\n\nmodelo = make_pipeline(\n    StandardScaler(),\n    MLPClassifier(hidden_layer_sizes=(16,),\n                  max_iter=1000, random_state=42)\n)\nmodelo.fit(X_train, y_train)\npred = modelo.predict(X_test)',challenge:'Si confundir una fruta defectuosa con una sana tiene un costo alto, ¿qué error y métrica revisarías?',solution:'Si «defectuosa» es la clase positiva, revisa los falsos negativos y recall. También mide cuántos falsos positivos puedes aceptar al aumentar la detección.'},
    labTitle:'Explora el umbral de decisión',labIntro:'Usa las cuatro frutas del ejemplo. Cambia el umbral y observa las predicciones y sus consecuencias.',lab:'threshold',
    questions:[{q:'¿Qué se ajusta normalmente durante el entrenamiento de una red?',options:['Las etiquetas reales de prueba.','Los pesos y sesgos.','El número de filas de prueba.'],answer:1,why:'La optimización modifica pesos y sesgos para reducir la pérdida en entrenamiento.'},{q:'Con p = 0,65 y umbral = 0,70, la predicción es…',options:['Clase positiva.','No es posible decidir.','Clase negativa.'],answer:2,why:'Con la regla p ≥ umbral, 0,65 no alcanza 0,70.'},{q:'¿Cómo se comparan dos clasificadores de forma justa?',options:['Con la misma partición y métricas pertinentes.','Evaluando cada uno en sus propios datos de entrenamiento.','Eligiendo el que tenga más capas.'],answer:0,why:'Mantener los mismos datos de evaluación permite comparar el desempeño en condiciones equivalentes.'}],
    resources:[['LEEME_CUADERNOS.md','Guía de ejecución','Orden de ejecución, datos y dependencias.'],['requirements.txt','Dependencias de Python','Versiones utilizadas para revisar los cuadernos.'],["7_KNN_paso_a_paso.ipynb", "KNN: vecinos y distancias", "Votación, selección de k y evaluación con validación cruzada."],["8_Arbol_decision_paso_a_paso.ipynb", "Árbol de decisión: reglas y sobreajuste", "Gini, profundidad, hojas y visualización del árbol."],["9_Regresion_logistica_paso_a_paso.ipynb", "Regresión logística: probabilidades", "Regularización, coeficientes y clasificación multiclase."],["10_Efecto_cambio_umbral.ipynb", "Efecto del cambio de umbral", "Precisión, recall, errores y costos; elección con validación."],["11_Escalamiento_comparacion_modelos.ipynb", "Escalamiento: comparación numérica", "Sin escala, StandardScaler y MinMaxScaler en cuatro modelos."],["2_Comparacion_clasificadores.ipynb", "Comparación de clasificadores y CV", "Práctica existente con pipelines y selección por F1 macro."],["AMPLIACION_SEMANA_3.md", "Ruta de prácticas de clasificación", "Orden sugerido, objetivos y datos de los nuevos cuadernos."],['1_Clasificadores_Aprendizaje_Automatico.ipynb','Clasificadores de aprendizaje automático','Teoría y ejercicios con scikit-learn.'],['3_clasificacion_red_neuronal.ipynb','Clasificación con red neuronal','Construcción de un clasificador neuronal.'],['Prueba_Corta_2_Clasificacion_Frutas.ipynb','Práctica: clasificación de frutas','Aplicación a un problema de clasificación.'],['tree_groups.csv','Datos para la red neuronal','Tres grupos de puntos para el clasificador neuronal.'],['data_frutas.csv','Datos de frutas','Datos para trabajar el caso de clasificación.']]
  },
  {
    id:4,title:'Ajuste y generalización',short:'Ajuste y generalización',description:'Reconoce el sobreajuste y mejora los modelos con regularización y ajuste de hiperparámetros.',color:'#aa6215',light:'#fcf0df',icon:'tune',
    objectives:['Detectar sobreajuste al comparar entrenamiento y validación.','Explicar L1, L2, dropout y parada temprana.','Elegir hiperparámetros sin utilizar el conjunto de prueba.'],
    concepts:[['Aprender patrones o memorizar','Un modelo subajustado tiene mal desempeño tanto en entrenamiento como en validación. Un modelo sobreajustado rinde muy bien en entrenamiento y peor en datos nuevos. Compara curvas y métricas, no solo la pérdida de entrenamiento.'],['Regularizar el aprendizaje','L1 y L2 penalizan los pesos en la función de pérdida. L1 favorece pesos nulos; L2 reduce su magnitud. Dropout desactiva aleatoriamente unidades durante entrenamiento. No se aplica del mismo modo durante la predicción.'],['Detenerse a tiempo','La parada temprana observa una métrica de validación y detiene el entrenamiento cuando deja de mejorar durante un número de épocas. Con restauración de los mejores pesos, se recupera el estado que tuvo el mejor resultado de validación.'],['Elegir hiperparámetros','Número de capas, unidades, tasa de aprendizaje y fuerza de regularización son decisiones de configuración. Herramientas como Keras Tuner exploran alternativas. La selección se hace con validación; prueba se usa al final.']],
    caution:'Consultar repetidamente la prueba para escoger configuraciones hace que deje de ser una evaluación independiente.',formula:'Pérdida con L2 = pérdida de datos + λ · Σw²\nMejor época = menor pérdida de validación\nPrueba final ≠ selección de hiperparámetros',
    exercise:{title:'Elegir la época de entrenamiento',intro:'Las pérdidas de entrenamiento en seis épocas son 0,70; 0,52; 0,39; 0,29; 0,21 y 0,16. Las de validación son 0,74; 0,57; 0,48; 0,46; 0,51 y 0,60.',steps:[['Identifica el mínimo de validación','El menor valor es 0,46 y ocurre en la época 4.'],['Reconoce la divergencia','Después de la época 4, entrenamiento sigue mejorando mientras validación empeora: es una señal de sobreajuste.'],['Selecciona el estado adecuado','Si se usa parada temprana y se restauran los mejores pesos, se conserva el estado de la época 4. El momento de detenerse también depende de patience y min_delta.']],code:'from tensorflow.keras.callbacks import EarlyStopping\n\nparada = EarlyStopping(\n    monitor="val_loss", patience=2,\n    restore_best_weights=True\n)\nmodelo.fit(\n    X_train, y_train,\n    validation_data=(X_val, y_val),\n    epochs=100, callbacks=[parada]\n)',challenge:'¿Por qué no seleccionar simplemente la última época, que tiene la menor pérdida de entrenamiento?',solution:'Porque el objetivo es generalizar. La pérdida de validación sugiere que las últimas épocas están aprendiendo particularidades del entrenamiento que no ayudan en datos nuevos.'},
    labTitle:'Lee las curvas de aprendizaje',labIntro:'Desplaza la época seleccionada y compara las dos pérdidas. Identifica dónde deja de mejorar la validación.',lab:'epochs',
    questions:[{q:'Entrenamiento mejora y validación empeora. ¿Qué sugiere?',options:['Que siempre se necesitan más épocas.','Posible sobreajuste.','Que ya no hace falta evaluar.'],answer:1,why:'La divergencia es una señal de que el modelo está perdiendo capacidad de generalizar.'},{q:'¿Cuál es el propósito de L2?',options:['Penalizar pesos grandes para controlar la complejidad.','Eliminar el conjunto de validación.','Aumentar siempre el número de capas.'],answer:0,why:'L2 añade una penalización proporcional a la suma de los cuadrados de los pesos.'},{q:'¿Qué conjunto se usa para seleccionar hiperparámetros?',options:['Prueba final.','Todos los datos mezclados con sus resultados de prueba.','Validación o particiones de validación cruzada.'],answer:2,why:'La selección usa validación. Prueba queda reservada para medir el desempeño final.'}],
    resources:[['LEEME_CUADERNOS.md','Guía de ejecución','Orden de ejecución, datos y dependencias.'],['requirements.txt','Dependencias de Python','Versiones utilizadas para revisar los cuadernos.'],['2_Sobreajuste_Redes_Neuronales_regresion.ipynb','Sobreajuste en regresión','Ejemplos de capacidad y generalización.'],['4_Autotuner_Red_Neuronal_Iris.ipynb','Ajuste automático de hiperparámetros','Exploración de configuraciones con Keras Tuner.'],['7_Regularizacion_Redes_Neuronales.ipynb','Regularización de redes neuronales','L1, L2 y dropout.']]
  },
  {
    id:5,title:'Clustering y segmentación',short:'Clustering y segmentación',description:'Descubre grupos en los datos y transforma agrupaciones en interpretaciones útiles.',color:'#0d7891',light:'#e0f2f7',icon:'clusters',
    objectives:['Explicar la asignación y actualización de K-Means.','Reconocer diferencias entre K-Means, DBSCAN y clustering jerárquico.','Interpretar agrupaciones sin confundirlas con etiquetas reales.'],
    concepts:[['Agrupar sin etiquetas','El clustering busca observaciones similares según sus características y una medida de distancia. Un grupo no equivale automáticamente a una categoría verdadera: necesita interpretación y evaluación en el contexto del problema.'],['Cómo funciona K-Means','Se eligen K centroides, se asigna cada punto al centro más cercano y se actualiza cada centro con la media de su grupo. Se repite hasta cumplir el criterio de parada. El resultado depende de la escala, la inicialización y K.'],['Otras formas de agrupar','DBSCAN usa densidad y puede identificar ruido; depende de eps y min_samples. El clustering jerárquico construye una estructura de agrupaciones que se puede representar con un dendrograma. Cada enfoque favorece estructuras diferentes.'],['Preparar e interpretar','Escala las variables si sus unidades hacen que una domine las distancias. Examina tamaños de grupos, centroides, visualizaciones y métricas como silueta cuando sean aplicables. Contrasta el resultado con el conocimiento del contexto.']],
    caution:'Los números de los clústeres son identificadores arbitrarios, no niveles de calidad ni un orden de importancia.',formula:'Asignación: centro más cercano\nNuevo centro = media de los puntos del grupo\nInercia = Σ distancia²(punto, su centro)',
    exercise:{title:'Segmentar clientes por frecuencia de visita',intro:'Usa seis clientes con 1, 2, 3, 8, 9 y 10 visitas al mes. En este ejemplo de una sola variable, K = 2 y los centroides iniciales son 1 y 8.',steps:[['Asigna al centro más cercano','Los clientes con 1, 2 y 3 visitas quedan en el grupo A. Los de 8, 9 y 10 visitas quedan en el grupo B.'],['Actualiza los centroides','Centro A = (1 + 2 + 3) / 3 = 2. Centro B = (8 + 9 + 10) / 3 = 9.'],['Interpreta los grupos','En estos datos, hay un grupo de menor frecuencia y otro de mayor frecuencia. La inercia final es 1 + 0 + 1 + 1 + 0 + 1 = 4. No sabemos aún su gasto ni su rentabilidad.']],code:'from sklearn.cluster import KMeans\nfrom sklearn.preprocessing import StandardScaler\n\n# X contiene solo características para agrupar\nX_scaled = StandardScaler().fit_transform(X)\nmodelo = KMeans(n_clusters=3, n_init=10, random_state=42)\ngrupos = modelo.fit_predict(X_scaled)\nprint("Inercia:", modelo.inertia_)',challenge:'¿Qué puede ocurrir si agrupas con edad (años) e ingreso (colones) sin escalar?',solution:'Las diferencias de ingreso pueden dominar la distancia debido a su magnitud. Escalar ayuda a equilibrar las variables; también debes decidir si ambas son relevantes para la segmentación.'},
    labTitle:'Una iteración de K-Means',labIntro:'Elige los centros iniciales para las visitas [1, 2, 3, 8, 9, 10]. Observa la asignación y las medias propuestas; pulsa el botón para actualizarlos.',lab:'kmeans',
    questions:[{q:'¿Cómo se actualiza un centro en K-Means?',options:['Con la media de las observaciones asignadas.','Con la etiqueta real de cada cliente.','Con el valor máximo de todo el conjunto.'],answer:0,why:'Cada centro es la media de las características de los puntos asignados a su grupo.'},{q:'¿Qué método puede marcar observaciones como ruido?',options:['La regresión lineal.','DBSCAN.','El cálculo de MAE.'],answer:1,why:'DBSCAN puede dejar sin clúster puntos que no cumplen las condiciones de densidad.'},{q:'¿Qué significa que un cliente esté en el clúster 2?',options:['Que es mejor cliente que uno del clúster 1.','Que tiene exactamente dos compras.','Que pertenece a un grupo cuyo identificador es 2.'],answer:2,why:'Los identificadores de clúster no tienen orden ni significado comercial por sí mismos.'}],
    resources:[['LEEME_CUADERNOS.md','Guía de ejecución','Orden de ejecución, datos y dependencias.'],['requirements.txt','Dependencias de Python','Versiones utilizadas para revisar los cuadernos.'],['1_teoria_clustering.ipynb','Teoría de clustering','K-Means y DBSCAN.'],['5_segmentacion_clientes.ipynb','Segmentación de clientes','Caso de uso para interpretar grupos.'],['Trabajo_Grupal_II_Kmeans_Iris_Clustering.ipynb','Práctica: K-Means con Iris','Actividad de agrupamiento.'],['Iris.csv','Datos de Iris','Dataset para el trabajo grupal de clustering.'],['Mall_Customers.csv','Datos de clientes','Datos para el caso de segmentación.']]
  },
  {
    id:6,title:'Selección de variables y PCA',short:'Selección de variables y PCA',description:'Reduce la complejidad e integra preparación, selección y evaluación en un proyecto.',color:'#a04a62',light:'#fae9ee',icon:'reduce',
    objectives:['Diferenciar selección de variables y reducción de dimensionalidad.','Interpretar información mutua y varianza explicada.','Construir un pipeline que evite fuga de información.'],
    concepts:[['Elegir variables relevantes','La información mutua mide dependencia entre una característica y el objetivo, incluyendo relaciones no lineales. No proporciona el signo de una relación ni demuestra causalidad. En scikit-learn se usa una función distinta para clasificación y regresión.'],['Seleccionar con SelectKBest','SelectKBest conserva K características según una puntuación. K es un hiperparámetro: se puede elegir mediante validación cruzada. La selección debe aprenderse dentro de cada partición de entrenamiento para evitar fuga.'],['Transformar con PCA','PCA construye nuevas variables, llamadas componentes principales, que maximizan sucesivamente la varianza y son ortogonales. No necesita la variable objetivo. Se suele escalar antes cuando las unidades de las características son diferentes.'],['Integrar el proceso','Un pipeline encadena preparación, selección o transformación y modelo. En el proyecto final, parte del problema de consumo de combustible, justifica las variables y evalúa el error fuera de entrenamiento. Documenta también las limitaciones.']],
    caution:'Explicar el 90 % de la varianza con PCA no significa obtener un 90 % de exactitud. PCA preserva variabilidad de las características, no garantiza capacidad predictiva.',formula:'Varianza acumulada = suma de proporciones por componente\nSelección: conserva variables originales\nPCA: crea nuevas combinaciones de variables',
    exercise:{title:'Elegir cuántos componentes conservar',intro:'Después de ajustar PCA, cuatro componentes explican el 50 %, 25 %, 15 % y 10 % de la varianza. Quieres conservar al menos el 90 %.',steps:[['Acumula la varianza','Con un componente: 50 %. Con dos: 75 %. Con tres: 90 %. Con cuatro: 100 %.'],['Elige el mínimo suficiente','Tres componentes alcanzan el objetivo del 90 %. Reducir a dos conservaría solo el 75 %.'],['Evalúa el modelo posterior','Si usarás los componentes para predecir, compara el desempeño en validación. Una alta varianza conservada no asegura una mejor predicción.']],code:'from sklearn.pipeline import Pipeline\nfrom sklearn.feature_selection import SelectKBest, mutual_info_regression\nfrom sklearn.linear_model import LinearRegression\nfrom sklearn.model_selection import GridSearchCV\n\npipe = Pipeline([\n    ("seleccion", SelectKBest(mutual_info_regression)),\n    ("modelo", LinearRegression())\n])\n# X_train debe contener al menos tres columnas numéricas sin NaN\nbusqueda = GridSearchCV(pipe, {"seleccion__k": [1, 2, 3]},\n                       cv=5, scoring="neg_mean_absolute_error")\nbusqueda.fit(X_train, y_train)\npred = busqueda.predict(X_test)',challenge:'¿Por qué seleccionar variables usando todo el conjunto antes de validación cruzada causa un problema?',solution:'La selección ya habría usado información de las filas que después se presentan como validación. Al incluirla en el pipeline, cada partición aprende la selección únicamente con sus datos de entrenamiento.'},
    labTitle:'Varianza explicada acumulada',labIntro:'Selecciona cuántos componentes conservar del ejemplo. Observa si alcanzas el objetivo de al menos 90 %.',lab:'pca',
    questions:[{q:'¿En qué se diferencia PCA de SelectKBest?',options:['PCA conserva siempre las columnas originales.','PCA crea componentes; SelectKBest conserva variables originales.','Los dos necesitan siempre etiquetas de clasificación.'],answer:1,why:'PCA transforma las características en nuevas combinaciones, mientras SelectKBest selecciona columnas originales.'},{q:'¿Cuántos componentes del ejemplo conservan al menos 90 %?',options:['Uno.','Dos.','Tres.'],answer:2,why:'50 % + 25 % + 15 % = 90 %.'},{q:'¿Dónde debe ajustarse la selección de variables durante validación cruzada?',options:['Dentro del pipeline en cada partición de entrenamiento.','Una sola vez con todos los datos, incluida prueba.','Solo después de observar el resultado de prueba.'],answer:0,why:'El pipeline evita que la selección use información de la partición que se está evaluando.'}],
    resources:[['LEEME_CUADERNOS.md','Guía de ejecución','Orden de ejecución, datos y dependencias.'],['requirements.txt','Dependencias de Python','Versiones utilizadas para revisar los cuadernos.'],['5_Ejercicio_Pipeline_Regresion_SelectKBest.ipynb','Práctica: pipeline y SelectKBest','Integra selección y regresión.'],['7_PCA_Analisis_de_Componentes_Principales.ipynb','Análisis de componentes principales','Teoría y ejemplo de PCA.'],['Proyecto_Final_Instructivo.ipynb','Instructivo del proyecto final','Predicción de consumo de combustible.'],['auto-mpg.csv','Datos de consumo de combustible','Datos del proyecto integrado.']]
  }
];

// Orden de prácticas por progresión pedagógica.
(() => {
 const COURSE=window.COURSE;
 const resources=COURSE[2].resources;
 const files=['LEEME_CUADERNOS.md','requirements.txt','AMPLIACION_SEMANA_3.md','1_Clasificadores_Aprendizaje_Automatico.ipynb','8_Arbol_decision_paso_a_paso.ipynb','7_KNN_paso_a_paso.ipynb','9_Regresion_logistica_paso_a_paso.ipynb','10_Efecto_cambio_umbral.ipynb','11_Escalamiento_comparacion_modelos.ipynb','2_Comparacion_clasificadores.ipynb','3_clasificacion_red_neuronal.ipynb','tree_groups.csv','Prueba_Corta_2_Clasificacion_Frutas.ipynb','data_frutas.csv'];
 COURSE[2].resources=files.map(file=>resources.find(r=>r[0]===file));
 COURSE[2].resources.forEach((r,i)=>{if(r[0].endsWith('.ipynb'))r[1]=`${files.slice(0,i+1).filter(f=>f.endsWith('.ipynb')).length}. ${r[1]}`;});
 COURSE[1].resources.splice(4,0,['5_Simple_regresion_red_neuronal.ipynb','Una sola neurona para regresión','Práctica de pesos, sesgo y predicción numérica.']);
})();
