// Secuencia didáctica aplicada después del contenido y sus figuras.
(() => {
 const single = lesson('Regresión con una sola neurona',
 'Relacionar una neurona lineal con la regresión y comprender cómo aprende sus pesos.',[
 'Una neurona recibe una o varias entradas x, multiplica cada una por un peso w y suma un sesgo b. El peso determina cuánto contribuye cada entrada; el sesgo es un término constante. Para regresión usamos activación lineal: la salida no transforma la suma, de modo que ŷ = wx + b con una entrada, o ŷ = Σwⱼxⱼ + b con varias.',
 'Una sola neurona lineal, sin capas ocultas, representa la misma familia de funciones que una regresión lineal. Una entrada produce regresión simple; varias entradas producen regresión múltiple. Tener varias entradas no significa tener varias neuronas. Esta arquitectura no puede aprender por sí sola una curva no lineal en las entradas originales.',
 'Entrenar significa cambiar pesos y sesgo para reducir una pérdida: una medida del error. Con MSE, o error cuadrático medio, se promedia (y − ŷ)². El gradiente indica cómo cambia esa pérdida con cada parámetro; el descenso de gradiente actualiza los parámetros en sentido contrario. La tasa de aprendizaje η controla el tamaño de cada paso.',
 'Un lote reúne los ejemplos usados para una actualización y una época recorre todo entrenamiento. Separa entrenamiento, validación y prueba antes de ajustar el escalamiento. Escalar consiste en transformar las magnitudes de las entradas usando estadísticas aprendidas solo en entrenamiento; puede facilitar las actualizaciones. La validación guía las decisiones de entrenamiento y la prueba queda para el final.',
 'En Keras, una capa Dense con units=1 y activation="linear", conectada directamente a las entradas, implementa esta neurona. Dense significa que la unidad recibe todas las entradas. Se puede entrenar con pérdida "mse" y un optimizador como SGD (descenso de gradiente estocástico). Compara MAE, RMSE y residuos con LinearRegression en las mismas particiones: entrenar por pasos no garantiza llegar exactamente al mismo ajuste.'
 ],[
 'Arquitectura: entradas → una neurona lineal → cantidad predicha; no hay capa oculta.',
 'Aprender: predecir, calcular MSE y actualizar w y b; repetir por lotes y épocas.',
 'Validar: observar el error en datos que no actualizan los pesos.',
 'Evaluar: comparar contra una referencia y regresión lineal en el test reservado.'
 ],'Un paso didáctico con un único caso: x = 2, y = 5, w = 1 y b = 0. Predicción = 2; pérdida = (5 − 2)² = 9. Los gradientes son ∂L/∂w = 2(2 − 5)·2 = −12 y ∂L/∂b = 2(2 − 5) = −6. Con η = 0,1, los nuevos valores son w = 2,2 y b = 0,6. La nueva predicción es 5 y la pérdida es 0 para este caso. No implica que el modelo generalice ni que esa tasa funcione siempre.',
 '¿Una neurona lineal con diez entradas puede representar relaciones no lineales por tener más pesos?',
 'No. Sigue calculando una combinación lineal más un sesgo. Para representar no linealidad hacen falta características transformadas o una arquitectura con activaciones no lineales.');
 LESSONS[2].splice(5,0,single);
 const v=CourseVisuals.data;
 v['2.7']=v['2.6'];
 v['2.6']={title:'Una neurona, un paso de aprendizaje',headers:['Cantidad','Antes','Después de actualizar'],rows:[['Peso w','1','2,2'],['Sesgo b','0','0,6'],['Predicción para x = 2','2','5'],['Error cuadrático del caso','9','0']],figure:()=>`<svg class="lesson-figure" viewBox="0 0 640 260" role="img" aria-label="Entrada x igual a 2, peso w y sesgo b, una neurona lineal y salida y predicha"><path d="M145 125h105m100 0h140" stroke="#2861a5" stroke-width="3"/><rect x="20" y="85" width="125" height="80" rx="12" fill="#e8f0fc"/><circle cx="300" cy="125" r="50" fill="#e2f3ed" stroke="#08796e" stroke-width="2"/><rect x="490" y="85" width="130" height="80" rx="12" fill="#e8f0fc"/><g text-anchor="middle"><text x="82" y="130">Entrada x = 2</text><text x="198" y="105">peso w</text><text x="300" y="130">wx + b</text><text x="555" y="130">Salida ŷ</text><text x="300" y="215">Una neurona lineal · sin capas ocultas</text></g></svg>`,caption:'Esquema de una entrada y una neurona. Los valores de la tabla son un paso exacto sobre un único caso; no describen una evaluación de generalización.'};

 const old=LESSONS[3].slice();
 // Índices originales: etiquetas, CV, escala, árbol, KNN, logística, umbral,
 // comparación, neuronas, entrenamiento, imágenes.
 const order=[0,9,10,6,7,8,4,1,2,3,5];
 const originalFigures=order.map(i=>v[`3.${i+1}`]);
 LESSONS[3]=order.map(i=>old[i]);
 originalFigures.forEach((fig,i)=>v[`3.${i+1}`]=fig);
 LESSONS[3][0].paragraphs.push('Vocabulario para la ruta: característica es una entrada X; etiqueta es la clase real y; parámetro es un valor que aprende el modelo; hiperparámetro es una configuración elegida antes de un ajuste. Entrenamiento aprende parámetros, validación permite elegir configuraciones y test evalúa al final. Generalizar es funcionar en casos nuevos; sobreajustar es aprender particularidades que no se mantienen fuera del entrenamiento. Fuga de información significa aprovechar durante el ajuste datos que debían quedar reservados.');
 LESSONS[3][0].paragraphs.push('Recordatorio de métricas: la matriz de confusión cuenta clases reales frente a predichas. Un falso positivo (FP) es una alerta incorrecta y un falso negativo (FN) es un positivo no detectado. Precisión = VP/(VP + FP); recall o sensibilidad = VP/(VP + FN); F1 es su media armónica. F1 macro promedia el F1 de las clases dándoles igual peso. Exactitud es la proporción total de aciertos. Una partición estratificada conserva aproximadamente las proporciones de clases.');
 LESSONS[3][1].paragraphs.unshift('Un pliegue es una parte de los datos de desarrollo. Desarrollo reúne los datos disponibles para entrenar y seleccionar antes del test. Un pipeline es una secuencia que agrupa preparación y modelo para ajustarlos juntos dentro de cada entrenamiento. Imputar significa completar faltantes; seleccionar variables significa conservar un subconjunto de entradas. Compararemos algoritmos, es decir, procedimientos para aprender una regla de predicción; se explicarán después de preparar esta evaluación.');
 LESSONS[3][2].paragraphs.unshift('Escalar cambia las magnitudes de columnas numéricas, no sus etiquetas. Un valor extremo es una observación muy alejada del resto. Optimizar es ajustar parámetros para reducir una pérdida o error. Regularizar añade una penalización a los parámetros para limitar la complejidad. RobustScaler usa mediana y rango intercuartílico, la diferencia entre los percentiles 75 y 25, como referencia menos sensible a extremos.');
 LESSONS[3][2].paragraphs.push('Los nombres que aparecen aquí se desarrollan en la ruta: KNN clasifica por vecinos cercanos; un árbol usa preguntas sucesivas; regresión logística estima probabilidades a partir de puntuaciones. SVM es una máquina de vectores de soporte, que busca separar clases con un margen; PCA crea combinaciones de variables que conservan variación y se estudia en la semana 6. Un bosque combina varios árboles. Estos tres últimos se mencionan como contexto, no son requisitos para hacer el cálculo de escala.');
 LESSONS[3][3].paragraphs.push('Entropía es otra medida de mezcla: −Σpᵢ log₂(pᵢ), tomando 0·log₂(0) como 0. Es cero si hay una sola clase. Profundidad cuenta niveles de divisiones y una hoja es un nodo sin nuevas divisiones.');
 LESSONS[3][5].paragraphs.push('Odds significa p/(1 − p), la razón entre probabilidad positiva y negativa; log-odds es su logaritmo natural. La pérdida logarítmica penaliza asignar poca probabilidad a la clase real. Softmax convierte varias puntuaciones zᵢ en exp(zᵢ)/Σexp(zⱼ), probabilidades que suman 1. Calibración significa que, entre muchos casos con probabilidad similar, la frecuencia real se aproxima a esa probabilidad.');
 LESSONS[3][6].paragraphs.push('Aquí sigmoide es la función 1/(1 + exp(−z)) explicada en regresión logística. Un umbral es el valor de corte para asignar una etiqueta. Las puntuaciones no siempre son probabilidades: hay que conocer la salida del modelo antes de interpretarla como tal.');
 LESSONS[3][7].paragraphs.push('Una frontera de decisión es el límite entre regiones a las que el modelo asigna clases diferentes. Ruido son variaciones o errores que dificultan reconocer el patrón; interpretabilidad es la facilidad de explicar la predicción.');
 LESSONS[3][8].paragraphs.push('Activación es la función aplicada a la suma ponderada. ReLU(z) = max(0, z); sigmoide produce una salida binaria entre 0 y 1 y softmax distribuye probabilidades entre clases. Una capa oculta está entre entrada y salida. Sesgo es el término constante b, no una medida de discriminación social en este contexto.');
 LESSONS[3][9].paragraphs.push('El gradiente reúne las derivadas de la pérdida respecto a los parámetros: indica cómo cambia el error al variarlos. La retropropagación calcula esas derivadas a través de las capas y el optimizador aplica la regla de actualización.');
 LESSONS[3][10].paragraphs.push('Un píxel es un elemento de la imagen; un canal almacena una componente, como rojo, verde o azul. Aplanar reorganiza la matriz como una lista de valores. Una capa densa conecta cada unidad con todas las entradas anteriores; un filtro convolucional es una pequeña matriz de pesos que se desplaza por la imagen para detectar patrones locales. Normalizar píxeles, por ejemplo dividir valores de 0–255 entre 255, cambia su escala de forma consistente.');
 const sections=CourseVisuals.section;
 CourseVisuals.section=(week,tab)=>week===3&&tab==='ejercicio'?CourseVisuals.render(3,6):sections(week,tab);

})();
