'use strict';
// Figuras vectoriales locales y tablas accesibles. Los datos numéricos son didácticos.
window.CourseVisuals = (() => {
 const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const colors = ['#08796e','#2468ac','#b05220','#8053a2'];
 const text = (x,y,s,extra='') => `<text x="${x}" y="${y}" ${extra}>${escape(s)}</text>`;
 const svg = (body,alt,height=320) => `<svg class="lesson-figure" viewBox="0 0 640 ${height}" role="img" aria-label="${escape(alt)}" xmlns="http://www.w3.org/2000/svg">${body}</svg>`;
 function flow(labels) {
  return svg(labels.map((l,i)=>{const x=30+(i%2)*320,y=28+Math.floor(i/2)*142;return `<rect x="${x}" y="${y}" width="280" height="100" rx="12" fill="${i===0?'#e2f3ed':'#eef3f8'}" stroke="#b8cbd8"/>${text(x+18,y+30,String(i+1).padStart(2,'0'),'class="figure-step"')}${text(x+18,y+65,l)}${i%2===0&&i+1<labels.length?`<path d="M${x+286} ${y+50}h26m-8-7 8 7-8 7" fill="none" stroke="#526c80" stroke-width="2"/>`:''}${i===1&&labels.length>2?'<path d="M490 136v19H170v10m-7-8 7 8 7-8" fill="none" stroke="#526c80" stroke-width="2"/>':''}`;}).join(''), labels.map((s,i)=>`${i+1}. ${s}`).join(' → '));
 }
 function bars(labels,values,unit='') {
  const max=Math.max(...values,1), step=55, height=values.length*step+66;
  return svg(labels.map((label,i)=>{const y=26+i*step;return `${text(154,y+23,label,'text-anchor="end"')}<rect x="170" y="${y}" width="${350*values[i]/max}" height="32" rx="5" fill="${colors[i%4]}"/>${text(179+350*values[i]/max,y+23,String(values[i])+unit)}`;}).join('')+text(170,height-12,unit===' %'?'Longitud proporcional al porcentaje':'Longitud proporcional al valor'),labels.map((l,i)=>`${l}: ${values[i]}${unit}`).join('; '),height);
 }
 function branches(root,left,right) {
  return svg(`<rect x="160" y="25" width="320" height="85" rx="12" fill="#e2f3ed" stroke="#b8cbd8"/>${text(320,75,root,'text-anchor="middle"')}<path d="M320 110v35H170v30m150-30h150v30" fill="none" stroke="#526c80" stroke-width="2"/>${[[30,left],[330,right]].map(([x,label])=>`<rect x="${x}" y="175" width="280" height="100" rx="12" fill="#eef3f8" stroke="#b8cbd8"/>${text(x+140,232,label,'text-anchor="middle"')}`).join('')}`,`${root}: alternativa 1, ${left}; alternativa 2, ${right}.`);
 }
 function lines(series,labels,yLabel='Pérdida',xLabel='Época') {
  const vals=series.flatMap(s=>s.values),max=Math.max(...vals)*1.15||1,min=Math.min(0,...vals),X=i=>75+i*515/(labels.length-1),Y=v=>245-(v-min)*190/(max-min);
  let body=`<path d="M75 40v205h520" stroke="#95aabd" fill="none"/>${text(75,24,yLabel)}${text(600,282,xLabel,'text-anchor="end"')}`;
  for(let i=0;i<4;i++){const v=min+(max-min)*i/3,y=Y(v);body+=`<path d="M75 ${y}h520" stroke="#e3eaf0"/>${text(62,y+5,v.toFixed(max>5?0:2),'text-anchor="end"')}`;}
  labels.forEach((l,i)=>{body+=text(X(i),267,l,'text-anchor="middle"');});
  series.forEach((s,i)=>{body+=`<polyline points="${s.values.map((v,j)=>`${X(j)},${Y(v)}`).join(' ')}" fill="none" stroke="${colors[i]}" stroke-width="3" ${i?'stroke-dasharray="7 4"':''}/>`;s.values.forEach((v,j)=>body+=`<circle cx="${X(j)}" cy="${Y(v)}" r="4" fill="${colors[i]}"/>`);body+=`<path d="M${80+i*260} 307h22" stroke="${colors[i]}" stroke-width="3" ${i?'stroke-dasharray="7 4"':''}/>${text(110+i*260,312,s.name)}`;});
  return svg(body,series.map(s=>`${s.name}: ${s.values.join(', ')}`).join('; '),340);
 }
 function scatter(points,{line=false,residuals=false,pca=false,xLabel='Variable X',yLabel='Variable Y',groups=false}={}) {
  const X=x=>70+x*49,Y=y=>258-y*20;
  let b=`<path d="M70 35v223h510" stroke="#8da6b8" fill="none"/>${text(70,23,yLabel)}${text(580,290,xLabel,'text-anchor="end"')}`;
  for(let i=0;i<=10;i+=2){b+=text(X(i),278,i,'text-anchor="middle"')+text(58,Y(i)+5,residuals?i-5:i,'text-anchor="end"');}
  if(line)b+=`<path d="M${X(0)} ${Y(1)}L${X(10)} ${Y(9)}" stroke="#b05220" stroke-width="3"/>`;
  if(residuals)b+=`<path d="M70 ${Y(5)}h500" stroke="#b05220" stroke-dasharray="6 4" stroke-width="2"/>`;
  if(pca)b+=`<path d="M${X(0)} ${Y(1)}L${X(10)} ${Y(9)}" stroke="#b05220" stroke-width="3"/>${text(X(8),Y(9)-10,'PC1')}`;
  points.forEach(([x,y,g=0])=>{b+=g===1?`<rect x="${X(x)-5}" y="${Y(y)-5}" width="10" height="10" fill="${colors[g]}"/>`:g===2?`<path d="M${X(x)} ${Y(y)-6}l6 11h-12Z" fill="${colors[g]}"/>`:`<circle cx="${X(x)}" cy="${Y(y)}" r="5" fill="${colors[g]}"/>`;});
  if(groups)b+=text(75,313,'● Grupo A     ■ Grupo B     ▲ Grupo C');
  return svg(b,`${xLabel} frente a ${yLabel}. ${pca?'PC1 sigue la dirección de mayor dispersión.':residuals?'Residuos a ambos lados de cero.':line?'Puntos alrededor de una recta de ajuste.':'Distribución de observaciones.'}`,330);
 }
 function network(dropout=false) {
  let b='';const ys=[[80,160,240],[50,120,190,260],[110,210]];
  for(let layer=0;layer<2;layer++)ys[layer].forEach((y,sourceIndex)=>ys[layer+1].forEach((z,j)=>{if(!dropout||!((layer===0&&j===1)||(layer===1&&sourceIndex===1)))b+=`<line x1="${90+layer*230}" y1="${y}" x2="${320+layer*230}" y2="${z}" stroke="#bdceda" stroke-width="1.5"/>`;}));
  ys.forEach((list,l)=>list.forEach((y,i)=>{b+=`<circle cx="${90+l*230}" cy="${y}" r="20" fill="${dropout&&l===1&&i===1?'#fff':'#e2f3ed'}" stroke="#08796e" stroke-width="2"/>${dropout&&l===1&&i===1?`<path d="M310 ${y-10}l20 20m0-20-20 20" stroke="#b05220" stroke-width="2"/>`:''}`;}));
  b+=text(90,310,'Entradas','text-anchor="middle"')+text(320,310,'Capa oculta','text-anchor="middle"')+text(550,310,'Salidas','text-anchor="middle"');
  return svg(b,dropout?'Red con una unidad oculta temporalmente desactivada durante entrenamiento.':'Tres entradas conectadas a cuatro unidades ocultas y dos salidas.',335);
 }
 function matrix(){return svg(text(360,28,'Predicción','text-anchor="middle"')+text(260,61,'Positivo','text-anchor="middle"')+text(465,61,'Negativo','text-anchor="middle"')+text(15,125,'Real +')+text(15,232,'Real −')+[[160,80,'VP = 30','#e2f3ed'],[370,80,'FN = 5','#fff0de'],[160,190,'FP = 10','#fff0de'],[370,190,'VN = 55','#e2f3ed']].map(([x,y,t,c])=>`<rect x="${x}" y="${y}" width="195" height="95" rx="8" fill="${c}"/>${text(x+98,y+55,t,'text-anchor="middle"')}`).join(''),'Matriz de 100 mensajes: VP 30, FN 5, FP 10, VN 55. Filas reales, columnas predichas.');}
 const points=[[1,2],[2,2.1],[3,3.7],[4,3.5],[5,5.6],[6,5.1],[7,7.2],[8,7],[9,8.7]];
 const grouped=[[1,2,0],[1.6,1.5,0],[2,2.6,0],[2.4,1.9,0],[6,7,1],[6.4,8,1],[7,7.3,1],[7.8,8.1,1],[8,2,2],[9,2.4,2],[8.7,3,2]];
 const losses=[{name:'Entrenamiento',values:[.70,.52,.39,.29,.21,.16]},{name:'Validación',values:[.74,.57,.48,.46,.51,.60]}];
 const spec=(title,headers,rows,figure,caption)=>({title,headers,rows,figure,caption});
 const data={
 '1.1':spec('De una observación a una predicción',['Elemento','Ejemplo','Función'],[['Fila','Una campaña','Unidad de análisis'],['X','Presupuesto y canal','Información previa'],['y','Ventas finales','Respuesta a predecir']],()=>flow(['Datos disponibles','Modelo ajustado','Predicción de ventas','Comparar con la realidad']),'Esquema conceptual. El objetivo no se introduce como una entrada del modelo.'),
 '1.2':spec('Elige el tipo de tarea',['Tarea','Respuesta disponible','Salida'],[['Regresión','Cantidad conocida','Número'],['Clasificación','Clase conocida','Categoría'],['Clustering','Sin etiquetas','Grupos']],()=>flow(['¿Hay respuestas?','Sí: supervisado','Cantidad: regresión','Clase: clasificación']),'Ruta del aprendizaje supervisado. Si no hay respuestas y se buscan grupos, se utiliza clustering.'),
 '1.3':spec('Controles de calidad',['Problema','Ejemplo','Acción'],[['Faltante','Ingreso vacío','Imputar con entrenamiento'],['Unidad','kg mezclados con g','Unificar unidades'],['Duplicado','Misma persona repetida','Revisar unidad y partición'],['Extremo','Peso inusual','Investigar antes de borrar']],()=>flow(['Revisar calidad','Separar conjuntos','Ajustar en entrenamiento','Transformar otros datos']),'Secuencia de preparación. Revisar la calidad no autoriza a aprender estadísticas de prueba.'),
 '1.4':spec('Tres conjuntos, tres funciones',['Conjunto','Ejemplo de 100 filas','Uso'],[['Entrenamiento',70,'Aprender parámetros'],['Validación',15,'Elegir configuración'],['Prueba',15,'Evaluación final']],()=>bars(['Entrenamiento','Validación','Prueba'],[70,15,15],' %'),'Distribución ilustrativa 70/15/15; no es una proporción obligatoria.'),
 '1.5':spec('Qué cuenta la matriz',['Resultado','Real','Predicción','Cantidad'],[['VP','Positivo','Positivo',30],['FN','Positivo','Negativo',5],['FP','Negativo','Positivo',10],['VN','Negativo','Negativo',55]],matrix,'Datos del ejercicio: «no deseado» es la clase positiva; total = 100 mensajes.'),
 '1.6':spec('Métricas del mismo ejemplo',['Métrica','Cálculo','Resultado'],[['Exactitud','85 / 100','85 %'],['Precisión','30 / 40','75 %'],['Recall','30 / 35','85,71 %'],['F1','60 / 75','80 %']],()=>bars(['Exactitud','Precisión','Recall','F1'],[85,75,85.71,80],' %'),'Las métricas usan la misma matriz de 100 mensajes. Ninguna resume por sí sola el costo de los errores.'),
 '2.1':spec('Define variables y unidades',['Variable','Significado','Unidad'],[['X','Inversión publicitaria','Decenas de miles de colones'],['y','Ventas observadas','Unidades vendidas'],['ŷ','Ventas estimadas','Unidades vendidas']],()=>flow(['Definir cantidad objetivo','Elegir entradas previas','Entrenar regresión','Medir error en prueba']),'Flujo de una regresión. La unidad del error debe coincidir con la del objetivo.'),
 '2.2':spec('La recta ŷ = 20 + 4x',['x','y real','ŷ','Residuo y − ŷ'],[[2,30,28,2],[4,34,36,-2],[6,47,44,3]],()=>lines([{name:'Observado',values:[30,34,47]},{name:'Predicho',values:[28,36,44]}],[2,4,6],'Ventas (unidades)','Inversión x'),'Valores exactos del ejercicio. La línea observada solo une tres casos; la predicha corresponde al modelo lineal.'),
 '2.3':spec('Una entrada por cada característica',['Término','Interpretación','Ejemplo'],[['β₀','Intercepto','Predicción con X = 0'],['β₁ × TV','Aporte condicional','Cambio por una unidad de TV'],['β₂ × Radio','Aporte condicional','Cambio manteniendo TV fijo']],()=>flow(['TV + Radio + Prensa','Combinación ponderada','Añadir intercepto','Predicción de ventas']),'Diagrama conceptual. Un coeficiente describe una asociación condicional; no prueba causalidad.'),
 '2.4':spec('Lee los residuos',['Patrón','Qué sugiere','Qué revisar'],[['Alrededor de cero','Sin sesgo visible','Magnitud y estabilidad'],['Forma curva','Relación no capturada','Transformaciones'],['Forma de embudo','Dispersión variable','Error por rangos']],()=>scatter([[1,5.4],[2,4.3],[3,5.8],[4,4.6],[5,5.3],[6,4.2],[7,5.5],[8,4.7],[9,5.1]],{residuals:true,xLabel:'Predicción',yLabel:'Residuo'}),'Residuos sintéticos. El eje vertical está centrado en cero; este gráfico no demuestra normalidad.'),
 '2.5':spec('Medir errores de 2, −2 y 3',['Métrica','Cálculo','Resultado'],[['MAE','(2 + 2 + 3) / 3','2,33'],['RMSE','√((4 + 4 + 9) / 3)','2,38'],['R²','1 − 17 / 158','0,8924']],()=>bars(['MAE','RMSE'],[2.33,2.38]),'Errores del ejercicio de ventas; MAE y RMSE se expresan en unidades vendidas. R² no comparte esas unidades.'),
 '2.6':spec('De la neurona a la regresión',['Componente','Función'],[['Pesos y sesgo','Aprender la relación'],['Capas ocultas','Representar no linealidad'],['Salida lineal','Predecir una cantidad'],['MSE o MAE','Medir el error']],()=>flow(['Entradas numéricas','Capas ocultas','Salida lineal ŷ','Pérdida de regresión']),'Arquitectura conceptual. Una sola neurona de salida lineal sin capas ocultas equivale a un modelo lineal.'),
 '3.1':spec('Las etiquetas son categorías',['Código','Categoría','¿Es una cantidad?'],[[0,'Manzana','No'],[1,'Mandarina','No'],[2,'Naranja','No'],[3,'Limón','No']],()=>flow(['Características de fruta','Clasificador','Probabilidades por clase','Clase con mayor valor']),'El orden numérico de las clases no implica distancia o jerarquía entre frutas.'),
 '3.2':spec('Compara en condiciones comunes',['Elemento','Regla'],[['Partición','Mismos ejemplos de evaluación'],['Escalado','Ajustado dentro de cada pliegue'],['Métrica','Misma definición y promedio'],['Selección','Validación; test al final']],()=>flow(['Pipelines candidatos','Validación cruzada','Seleccionar por CV','Evaluar el elegido en test']),'Proceso conceptual; no se asigna un ganador sin ejecutar la comparación.'),
 '3.3':spec('Capas y activaciones',['Elemento','Operación','Uso'],[['Neurona','z = Σwᵢxᵢ + b','Combina entradas'],['ReLU','max(0, z)','Capa oculta'],['Sigmoid','Valor entre 0 y 1','Salida binaria'],['Softmax','Probabilidades que suman 1','Salida multiclase']],()=>network(),'Red ilustrativa de 3 entradas, 4 unidades ocultas y 2 salidas. Las líneas representan pesos aprendidos.'),
 '3.4':spec('Un ciclo de entrenamiento',['Paso','Qué sucede'],[['Propagación','Calcular predicciones'],['Pérdida','Comparar con las etiquetas'],['Gradientes','Calcular derivadas'],['Actualización','Modificar pesos y sesgos']],()=>flow(['Predicción','Calcular pérdida','Retropropagación','Actualizar pesos']),'El ciclo se repite por lotes. Una época recorre el conjunto de entrenamiento.'),
 '3.5':spec('Cambiar el umbral cambia decisiones',['Fruta','p(A)','Real','Umbral 0,50','Umbral 0,70'],[['1','0,20',0,0,0],['2','0,45',1,0,0],['3','0,65',0,1,0],['4','0,90',1,1,1]],()=>bars(['Fruta 1','Fruta 2','Fruta 3','Fruta 4'],[20,45,65,90],' %'),'Probabilidades del ejercicio. El umbral 0,70 exige al menos 70 % para predecir la clase positiva.'),
 '3.6':spec('Preprocesamiento de una imagen',['Etapa','Ejemplo','Comprobación'],[['Tamaño','28 × 28','Forma esperada'],['Canales','1 en gris','Conservar dimensión'],['Escala','0…255 → 0…1','Dividir entre 255'],['Lote','(1, 28, 28, 1)','Una imagen']],()=>flow(['Imagen original','Tamaño y canales','Normalizar píxeles','Modelo → clase']),'La misma transformación se aplica al entrenar y al predecir. Flatten y convolución son operaciones diferentes.'),
 '4.1':spec('Diagnóstico del ajuste',['Situación','Entrenamiento','Validación'],[['Subajuste','Error alto','Error alto'],['Generalización útil','Error bajo','Error comparable'],['Posible sobreajuste','Error sigue bajando','Error empieza a subir']],()=>lines(losses,[1,2,3,4,5,6]),'Ejemplo numérico del ejercicio: desde la época 5 empeora validación mientras mejora entrenamiento.'),
 '4.3':spec('Dos penalizaciones distintas',['Método','Penalización','Efecto típico'],[['L1','λ Σ|w|','Favorece pesos nulos'],['L2','λ Σw²','Reduce pesos grandes'],['λ','Intensidad','Se elige con validación']],()=>flow(['Pérdida de datos','Añadir penalización','Optimizar total','Validar intensidad λ']),'Esquema conceptual. Una penalización demasiado fuerte puede producir subajuste.'),
 '4.4':spec('Dropout según el momento',['Momento','Comportamiento'],[['Entrenamiento','Desactiva unidades al azar'],['Predicción','Utiliza la red completa'],['Tasa','Fracción que se desactiva'],['Interpretación','No borra neuronas permanentemente']],()=>network(true),'Una unidad está tachada solo para ilustrar un paso de entrenamiento; la máscara cambia entre pasos.'),
 '4.5':spec('Qué se aprende y qué se elige',['Tipo','Ejemplos','Cómo se determina'],[['Parámetro','Pesos y sesgos','Optimizador'],['Hiperparámetro','Capas, unidades, tasa','Búsqueda con validación'],['Métrica de selección','F1 o MAE','Según el problema'],['Prueba','Estimación final','Después de seleccionar']],()=>flow(['Definir espacio','Entrenar candidatos','Comparar validación','Evaluar final en test']),'Cada candidato debe respetar las mismas particiones. El test no guía la búsqueda.'),
 '4.6':spec('Qué conservar para predecir',['Artefacto','Por qué importa'],[['Modelo','Pesos y arquitectura'],['Transformaciones','Misma escala y codificación'],['Columnas','Nombres, orden y unidades'],['Metadatos','Versiones y clases']],()=>flow(['Guardar modelo','Guardar preparación','Cargar ambos','Predecir nuevos casos']),'No basta con guardar los pesos: una entrada transformada de otra forma puede invalidar la predicción.'),
 '5.1':spec('La escala modifica las distancias',['Variable','Rango ilustrativo','Riesgo'],[['Ingreso','1 000…100 000','Puede dominar'],['Edad','18…80','Menor magnitud'],['Visitas','0…20','Otra unidad']],()=>scatter(grouped,{groups:true,xLabel:'Característica escalada 1',yLabel:'Característica escalada 2'}),'Grupos sintéticos. Los ejes son ilustrativos; la forma y las distancias dependen del escalado.'),
 '5.2':spec('Una iteración de K-Means',['Grupo','Valores asignados','Nuevo centro'],[['A','1, 2, 3',2],['B','8, 9, 10',9]],()=>flow(['Centros iniciales: 1 y 8','Asignar por cercanía','Medias: 2 y 9','Repetir asignación']),'Ejercicio de visitas mensuales. Los centroides son medias, no necesariamente clientes reales.'),
 '5.3':spec('Comparar cantidades de grupos',['k','Inercia ilustrativa','Silueta ilustrativa'],[[2,120,.42],[3,65,.61],[4,48,.52],[5,39,.44]],()=>lines([{name:'Silueta',values:[.42,.61,.52,.44]}],[2,3,4,5],'Silueta media','k'),'Datos sintéticos: aquí k=3 maximiza silueta. El codo y la silueta pueden sugerir valores diferentes.'),
 '5.4':spec('DBSCAN distingue densidad y ruido',['Concepto','Significado'],[['eps','Radio de vecindad'],['min_samples','Mínimo de puntos contando el propio'],['Núcleo','Cumple el mínimo'],['Ruido (−1)','No pertenece a un grupo']],()=>scatter([...grouped.slice(0,8),[9,1,2]],{groups:true,xLabel:'X',yLabel:'Y'}),'Esquema de dos grupos densos (A y B) y un punto aislado (triángulo C, candidato a ruido). No es una ejecución de DBSCAN.'),
 '5.5':spec('Formas de medir distancia entre grupos',['Enlace','Distancia usada'],[['Single','Menor distancia entre pares'],['Complete','Mayor distancia entre pares'],['Average','Promedio entre pares'],['Corte','Define los grupos finales']],()=>svg('<path d="M90 270v-90h130v90M155 180v-90h275v90M365 270v-90h130v90M430 180V90" fill="none" stroke="#08796e" stroke-width="3"/><path d="M50 135h500" stroke="#b05220" stroke-dasharray="7 5"/>'+text(90,297,'A','text-anchor="middle"')+text(220,297,'B','text-anchor="middle"')+text(365,297,'C','text-anchor="middle"')+text(495,297,'D','text-anchor="middle"')+text(70,40,'Distancia de fusión ↑')+text(510,129,'Corte'),'Dendrograma conceptual: A y B se unen; C y D se unen; el corte intermedio produce dos grupos.'),'Dendrograma conceptual sin escala numérica. Un corte entre ambas alturas de fusión produce dos grupos.'),
 '5.6':spec('Del grupo a una descripción útil',['Grupo','Visitas medias','Descripción cauta'],[['A',2,'Menor frecuencia en esta muestra'],['B',9,'Mayor frecuencia en esta muestra']],()=>bars(['Grupo A','Grupo B'],[2,9]),'Centros del ejercicio de seis clientes. Los identificadores A y B no son categorías universales.'),
 '6.1':spec('Seleccionar no es transformar',['Operación','Entrada','Salida'],[['Selección','X₁, X₂, X₃','Subconjunto, p. ej. X₁ y X₃'],['PCA','X₁, X₂, X₃','Combinaciones: PC1, PC2'],['Interpretación','Variables originales','Más directa al seleccionar']],()=>flow(['Variables originales','Elegir una estrategia','Selección: conservar','PCA: combinar']),'Las dos opciones reducen dimensionalidad de formas distintas; no forman una secuencia obligatoria.'),
 '6.2':spec('Interpretar información mutua',['Variable','MI ilustrativa','Lectura'],[['A',.45,'Mayor dependencia estimada'],['B',.22,'Dependencia menor'],['C',.01,'Cercana a cero']],()=>bars(['Variable A','Variable B','Variable C'],[.45,.22,.01]),'Puntuaciones sintéticas de MI, no porcentajes ni coeficientes causales. Un valor estimado cercano a cero no prueba independencia.'),
 '6.3':spec('Selección dentro de la validación',['Paso','Datos permitidos'],[['Ajustar escalador','Entrenamiento del pliegue'],['Calcular MI','Entrenamiento del pliegue'],['Seleccionar k','Comparación entre pliegues'],['Evaluación final','Test reservado']],()=>flow(['Dividir un pliegue','Ajustar pipeline en train','Medir en validación','Repetir y escoger k']),'SelectKBest forma parte del pipeline; calcular sus puntuaciones antes de CV filtraría información.'),
 '6.4':spec('Los componentes de PCA',['Elemento','Función'],[['Escalado','Hacer comparables las unidades'],['PC1','Máxima varianza proyectada'],['PC2','Ortogonal a PC1'],['Pesos','Combinación de variables']],()=>scatter(points,{pca:true,xLabel:'Variable 1',yLabel:'Variable 2'}),'Nube sintética: la línea representa aproximadamente PC1. PCA usa las entradas, no la variable objetivo.'),
 '6.5':spec('Varianza individual y acumulada',['Componente','Individual','Acumulada'],[['PC1','50 %','50 %'],['PC2','25 %','75 %'],['PC3','15 %','90 %'],['PC4','10 %','100 %']],()=>bars(['PC1','PC2','PC3','PC4'],[50,25,15,10],' %'),'Datos del ejercicio. Se necesitan tres componentes para conservar al menos el 90 % de la varianza.'),
 '6.6':spec('Un proceso reproducible',['Etapa','Evidencia que debes guardar'],[['Separación','Índices y semilla'],['Selección','MI calculada con entrenamiento'],['Modelo','Configuración y línea base'],['Evaluación','MAE, RMSE y residuos de test']],()=>flow(['Separar los datos','Preparar y seleccionar','Entrenar y validar','Evaluar y documentar']),'Esquema del proyecto. Mantenga las mismas particiones durante todo el proceso.')
 };
 data['4.2']=spec('Conservar el mejor punto',['Época','Train','Validación'],[1,2,3,4,5,6].map((x,i)=>[x,losses[0].values[i],losses[1].values[i]]),()=>lines(losses,[1,2,3,4,5,6]),'La menor pérdida de validación es 0,46 en la época 4. La paciencia determina cuándo detener; restore_best_weights recupera los mejores pesos.');
 data['1.2'].figure=()=>branches('¿Hay respuestas conocidas?','Sí: supervisado','No: no supervisado');
 data['1.2'].caption='Con respuestas conocidas: regresión para cantidades y clasificación para categorías. Sin etiquetas: agrupamiento o reducción de dimensionalidad, según el objetivo.';
 data['6.1'].figure=()=>branches('Reducir el número de variables','Seleccionar originales','Combinar con PCA');
 data['3.7']=spec('De una regla a una hoja',['Elemento','Función','Ejemplo'],[['Nodo','Pregunta sobre una variable','¿Peso ≤ 140 g?'],['Rama','Resultado de la pregunta','Sí / No'],['Hoja','Clase mayoritaria','8 mandarinas y 2 naranjas → mandarina'],['max_depth','Límite de complejidad','Comparar 2, 3 y 5 con CV']],()=>branches('¿Peso ≤ 140 g?','Sí → mandarina','No → naranja'),'Árbol ilustrativo de una sola división. Las etiquetas de hoja y el umbral son didácticos, no reglas universales. La hoja izquierda tiene Gini 0,32.');
 data['3.8']=spec('Votación de los tres vecinos',['Vecino','Distancia','Etiqueta'],[['1','0,20','Manzana'],['2','0,35','Naranja'],['3','0,50','Manzana']],()=>bars(['Manzana','Naranja'],[2,1]),'Voto uniforme con k = 3: manzana obtiene 2 votos y naranja 1. Las distancias corresponden a características ya escaladas.');
 data['3.8'].figure=()=>svg(`
 <path d="M50 45v295h340" fill="none" stroke="#8da6b8"/>
 ${text(50,28,'Característica 2 (escalada)')}${text(390,368,'Característica 1 (escalada)','text-anchor="end"')}
 <circle cx="230" cy="200" r="100" fill="#e2f3ed" fill-opacity=".55" stroke="#08796e" stroke-dasharray="6 5"/>
 <path d="M230 200h40" stroke="#2468ac" stroke-width="4"/>
 <path d="M230 200v-70" stroke="#b05220" stroke-width="4"/>
 <path d="M230 200H130" stroke="#08796e" stroke-width="4"/>
 <circle cx="270" cy="200" r="9" fill="#08796e"/><circle cx="130" cy="200" r="9" fill="#08796e"/>
 <rect x="221" y="121" width="18" height="18" rx="2" fill="#b05220"/>
 <circle cx="85" cy="90" r="8" fill="#08796e"/><circle cx="120" cy="305" r="8" fill="#08796e"/>
 <rect x="340" y="75" width="16" height="16" fill="#b05220"/><rect x="350" y="292" width="16" height="16" fill="#b05220"/>
 <path d="M230 188l12 12-12 12-12-12Z" fill="#8053a2" stroke="white" stroke-width="2"/>
 ${text(245,270,'Caso nuevo ?')}
 <path d="M250 200l38 28" stroke="#2468ac" stroke-width="2" fill="none"/>
 <rect x="276" y="218" width="120" height="34" rx="7" fill="white" stroke="#2468ac" stroke-width="2"/>
 ${text(336,242,'d₁ = 0,20','text-anchor="middle" style="font-size:20px;font-weight:700;fill:#2468ac"')}
 <path d="M230 160h18" stroke="#b05220" stroke-width="2"/>
 <rect x="248" y="143" width="120" height="34" rx="7" fill="white" stroke="#b05220" stroke-width="2"/>
 ${text(308,167,'d₂ = 0,35','text-anchor="middle" style="font-size:20px;font-weight:700;fill:#b05220"')}
 <path d="M175 200v-16" stroke="#08796e" stroke-width="2"/>
 <rect x="80" y="149" width="120" height="34" rx="7" fill="white" stroke="#08796e" stroke-width="2"/>
 ${text(140,173,'d₃ = 0,50','text-anchor="middle" style="font-size:20px;font-weight:700;fill:#08796e"')}
 <rect x="417" y="76" width="205" height="225" rx="12" fill="#eef3f8"/>
 ${text(435,106,'k = 3 vecinos')}${text(435,145,'● Manzana: 2 votos')}${text(435,181,'■ Naranja: 1 voto')}
 ${text(435,230,'Clase predicha:')}${text(435,263,'MANZANA')}
 ${text(50,402,'● Manzana     ■ Naranja     ◆ Caso sin etiqueta')}
 `,'KNN con k igual a 3: el rombo es un caso nuevo. Sus vecinos a distancias 0,20, 0,35 y 0,50 son manzana, naranja y manzana. Gana manzana con dos votos. Los puntos fuera del círculo no votan.',425);
 data['3.8'].caption='Ejemplo geométrico con igual escala en ambos ejes: el círculo llega hasta el tercer vecino (distancia 0,50). Las líneas unen el caso nuevo con los tres vecinos que votan. Los demás puntos quedan fuera de la votación. No es una frontera aprendida ni un radio fijo: con otra consulta el radio puede cambiar.';
 data['3.9']=spec('De la puntuación a la probabilidad',['z','Sigmoide aproximada','Clase con umbral 0,50'],[['−4','0,018','0'],['−2','0,119','0'],['0','0,500','1'],['2','0,881','1'],['4','0,982','1']],()=>lines([{name:'p(y = 1 | x)',values:[-4,-3,-2,-1,0,1,2,3,4].map(z=>1/(1+Math.exp(-z)))}],[-4,-3,-2,-1,0,1,2,3,4],'Probabilidad estimada','Puntuación z'),'Sigmoide calculada en nueve puntos unidos por segmentos. En z = 0, p = 0,50; la probabilidad siempre está entre 0 y 1.');
 data['3.10']=spec('Cinco rondas, un test reservado',['Ronda','Entrena','Valida','F1 macro ilustrativo'],[['1','Pliegues 2, 3, 4, 5','Pliegue 1','0,80'],['2','Pliegues 1, 3, 4, 5','Pliegue 2','0,85'],['3','Pliegues 1, 2, 4, 5','Pliegue 3','0,75'],['4','Pliegues 1, 2, 3, 5','Pliegue 4','0,90'],['5','Pliegues 1, 2, 3, 4','Pliegue 5','0,80']],()=>svg(Array.from({length:5},(_,c)=>text(187+c*74,28,'P'+(c+1),'text-anchor="middle"')).join('')+Array.from({length:5},(_,r)=>text(22,64+r*43,`Ronda ${r+1}`)+Array.from({length:5},(_,c)=>`<rect x="${155+c*74}" y="${40+r*43}" width="64" height="32" rx="5" fill="${r===c?'#b05220':'#08796e'}"/>${text(187+c*74,62+r*43,r===c?'V':'E','text-anchor="middle" style="fill:white"')}`).join('')).join('')+text(24,287,'E: entrenamiento · V: validación')+text(24,313,'Test: separado durante todas las rondas'),'Matriz de cinco rondas. En cada fila un pliegue valida y cuatro entrenan; el test no participa.',340),'Cada fila representa un modelo nuevo. Ejemplo con 80 casos de desarrollo: 64 entrenan y 16 validan en cada ronda. Los 20 casos de test quedan fuera.');
 data['3.11']=spec('Comparar los dos escaladores',['Criterio','StandardScaler','MinMaxScaler'],[['Fórmula','(x − media) / desviación','(x − mínimo) / (máximo − mínimo)'],['Resultado en entrenamiento','Media 0 y varianza 1 si no es constante','Rango [0, 1] por defecto'],['Uso inicial habitual','Logística regularizada, SVM, PCA','Entradas en un intervalo común'],['KNN y redes','Comparar con validación cruzada','Comparar con validación cruzada'],['Valores extremos','Sensible','Sensible; comprime valores centrales'],['Caso nuevo x = 40','2,449','1,5']],()=>lines([{name:'StandardScaler',values:[-1.224744871,0,1.224744871,2.449489743]},{name:'MinMaxScaler',values:[0,.5,1,1.5]}],[10,20,30,40],'Valor transformado','Valor original x'),'Cálculos con entrenamiento [10, 20, 30]. El punto 40 es nuevo: se transforma sin reajustar. Las líneas muestran dos escalas distintas, no desempeños de modelos.');
 function table(title,headers,rows){return `<div class="visual-table-wrap" role="region" aria-label="${escape(title)}" tabindex="0"><table class="visual-table"><caption>${escape(title)}</caption><thead><tr>${headers.map(h=>`<th scope="col">${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>i===0?`<th scope="row">${escape(v)}</th>`:`<td>${escape(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
 function render(w,index){const v=data[`${w}.${index+1}`];if(!v)return '';return `<section class="visual-support"><p class="micro-label">OBSERVA Y COMPARA</p><h3>${escape(v.title)}</h3>${table('Tabla de apoyo · '+v.title,v.headers,v.rows)}<figure tabindex="0" aria-label="Figura de apoyo; desplazable horizontalmente en pantallas pequeñas">${v.figure()}<figcaption>${escape(v.caption)}</figcaption></figure></section>`;}
 const exerciseIndex={1:4,2:1,3:4,4:1,5:1,6:4};
 function section(w,tab){
  if(tab==='ejercicio')return render(w,exerciseIndex[w]);
  if(tab==='practica')return `<section class="panel visual-support"><h2>Cómo registrar tu experimento</h2>${table('Compara tus pruebas',['Paso','Qué registrar'],[['Antes','Valor inicial y predicción de lo que ocurrirá'],['Cambio','Una sola variable o decisión'],['Resultado','Métrica o figura observada'],['Interpretación','Explicación y límite del ejemplo']])}<figure tabindex="0" aria-label="Figura de apoyo; desplazable horizontalmente en pantallas pequeñas">${flow(['Predecir un efecto','Cambiar un control','Observar el gráfico','Explicar el resultado'])}<figcaption>Usa el laboratorio interactivo de arriba. Registra tus valores; esta guía no inventa resultados.</figcaption></figure></section>`;
  if(tab==='recursos')return `<section class="panel visual-support"><h2>Prepara tu práctica con Python</h2>${table('Archivos y uso',['Material','Para qué sirve','Cómo utilizarlo'],[['.ipynb','Teoría y código','Abrir en Jupyter o Colab'],['.csv','Observaciones','Guardar junto al cuaderno'],['requirements.txt','Dependencias','Instalar en un entorno virtual'],['LEEME_CUADERNOS.md','Guía','Revisar antes de ejecutar']])}<figure tabindex="0" aria-label="Figura de apoyo; desplazable horizontalmente en pantallas pequeñas">${flow(['Descargar los archivos','Preparar el entorno','Ejecutar en orden','Interpretar las salidas'])}<figcaption>Los cuadernos se ejecutan en Python. Las prácticas de la web funcionan directamente en el navegador.</figcaption></figure></section>`;
  return '';
 }
 return {render,section,data};
})();
