window.Week6Labs=(()=>{
 const mi=n=>{const p=n/10;return 1+[p,1-p].reduce((s,v)=>s+(v?v*Math.log2(v):0),0);};
 const pts=[[-3,-2],[-2,-2],[-1,0],[0,-1],[1,1],[2,1],[3,3]];
 function projection(degrees){const means=[0,1].map(j=>pts.reduce((s,p)=>s+p[j],0)/pts.length),a=degrees*Math.PI/180,u=[Math.cos(a),Math.sin(a)],center=pts.map(p=>p.map((x,j)=>x-means[j]));const recon=center.map(p=>{const score=p[0]*u[0]+p[1]*u[1];return [score*u[0],score*u[1]];});const total=center.reduce((s,p)=>s+p[0]**2+p[1]**2,0),error=center.reduce((s,p,i)=>s+(p[0]-recon[i][0])**2+(p[1]-recon[i][1])**2,0);return {center,recon,error:error/pts.length,retained:100*(1-error/total)};}
 function mount(host){
  const s=document.createElement('section');s.className='panel';s.id='mi-lab';s.innerHTML=`<h2>Información mutua: dependencia no significa causalidad</h2><p>Una muestra sintética tiene 20 casos: diez con objetivo y = 0 y diez con y = 1. Cambia cuántos coinciden con una característica binaria X dentro de cada clase. La información mutua discreta se calcula con las frecuencias de esta tabla: MI = Σp(x,y) log₂[p(x,y)/(p(x)p(y))]. Se expresa en bits; los términos con frecuencia cero aportan cero.</p><label for="mi-matches">Coincidencias por clase (de 10)</label><input type="range" id="mi-matches" min="0" max="10" value="8"><div id="mi-out" aria-live="polite"></div><p>Prueba 10, 5 y 0 coincidencias. ¿Por qué una relación inversa perfecta también aporta información? Esta MI exacta para variables binarias no es el estimador de variables continuas de los notebooks.</p>`;
  const k=document.createElement('section');k.className='panel';k.id='selection-lab';k.innerHTML=`<h2>Selecciona k sin mirar el test</h2><p>Resultados ilustrativos de cinco pliegues de validación para un pipeline con SelectKBest y un clasificador. En cada pliegue, la selección aprende solo de su entrenamiento. Aquí exploras una tabla didáctica fija: no se entrena un modelo en el navegador. La k indica variables conservadas, no vecinos ni pliegues.</p><label for="selection-k">Número de variables k</label><input type="range" id="selection-k" min="1" max="4" value="1"><div id="selection-out" aria-live="polite"></div><p>Elige la mayor media de F1 macro, observa su variabilidad y explica por qué conservar más variables no garantiza una mejora. Después se reajustaría el pipeline elegido con todo desarrollo y se evaluaría una sola vez en test, que no aparece aquí.</p>`;
  const p=document.createElement('section');p.className='panel';p.id='projection-lab';p.innerHTML=`<h2>PCA: proyecta y reconstruye en una dimensión</h2><p>La nube se centra restando la media de cada variable. Gira una dirección, proyecta los puntos sobre ella y observa el error de reconstrucción. La primera componente principal es la dirección que conserva la mayor varianza, equivalente aquí a minimizar ese error. Las dos variables están en unidades comparables.</p><label for="pca-angle">Ángulo de la dirección (grados)</label><input id="pca-angle" type="range" min="0" max="180" value="0"><button type="button" id="pca-optimal">Usar dirección de PC1</button><div id="projection-out" aria-live="polite"></div><figure id="projection-plot"></figure><p>Los círculos son datos centrados; los cuadrados son reconstrucciones. Los segmentos muestran la información perdida. Una dirección arbitraria no se llama PC1: solo la de máxima varianza. PCA no utiliza etiquetas ni garantiza buena predicción de un objetivo.</p>`;
  host.append(s,k,p);
  const updateMI=()=>{const n=Number(s.querySelector('input').value),value=mi(n);s.querySelector('#mi-out').innerHTML=`<p>Coincidencias: ${n}/10 por clase · <strong>MI = ${value.toFixed(3)} bits</strong></p><table><caption>Frecuencias conjuntas (20 casos)</caption><thead><tr><th></th><th>y = 0</th><th>y = 1</th></tr></thead><tbody><tr><th>X = 0</th><td>${n}</td><td>${10-n}</td></tr><tr><th>X = 1</th><td>${10-n}</td><td>${n}</td></tr></tbody></table><meter min="0" max="1" value="${value}" aria-label="Información mutua en bits">${value}</meter><p>${n===5?'Independencia en esta tabla: conocer X no cambia las proporciones de y.':n===0?'Relación inversa perfecta: conocer X permite deducir y.':n===10?'Relación directa perfecta: X coincide con y.':'Hay dependencia en la muestra; no demuestra causalidad.'}</p>`;};
  const scores=[[.7,.75,.8,.75,.7],[.85,.9,.85,.9,.85],[.8,.85,.85,.8,.85],[.75,.8,.8,.85,.75]],means=scores.map(a=>a.reduce((s,x)=>s+x,0)/5);
  const updateK=()=>{const i=Number(k.querySelector('input').value)-1,sd=Math.sqrt(scores[i].reduce((s,x)=>s+(x-means[i])**2,0)/5);k.querySelector('#selection-out').innerHTML=`<p>k = ${i+1}: media <strong>${means[i].toFixed(3)}</strong>; desviación entre pliegues ${sd.toFixed(3)} (no es un intervalo de confianza).</p><table><caption>F1 macro ilustrativo de validación</caption><thead><tr><th>k</th><th>P1</th><th>P2</th><th>P3</th><th>P4</th><th>P5</th><th>Media</th></tr></thead><tbody>${scores.map((a,j)=>`<tr ${i===j?'style="background:#e2f3ed"':''}><th>${j+1}</th>${a.map(x=>`<td>${x.toFixed(2)}</td>`).join('')}<td>${means[j].toFixed(3)}</td></tr>`).join('')}</tbody></table><p>${i===1?'k = 2 obtiene la mayor media en este ejemplo.':'Compara la media con las otras opciones antes de elegir.'}</p>`;};
  const updateP=()=>{const angle=Number(p.querySelector('input').value),v=projection(angle),X=x=>260+x*45,Y=y=>190-y*45;const a=angle*Math.PI/180;p.querySelector('#projection-out').innerHTML=`<p>Ángulo ${angle}° · variación conservada: <strong>${v.retained.toFixed(2)} %</strong> · error cuadrático medio de reconstrucción por caso: <strong>${v.error.toFixed(4)}</strong></p>`;p.querySelector('#projection-plot').innerHTML=`<svg viewBox="0 0 520 380" style="width:100%" role="img" aria-label="Proyección y reconstrucción con ángulo ${angle} grados"><path d="M${X(-4*Math.cos(a))} ${Y(-4*Math.sin(a))}L${X(4*Math.cos(a))} ${Y(4*Math.sin(a))}" stroke="#754ab0" stroke-width="2"/>${v.center.map((pt,i)=>`<path d="M${X(pt[0])} ${Y(pt[1])}L${X(v.recon[i][0])} ${Y(v.recon[i][1])}" stroke="#aaa"/><circle cx="${X(pt[0])}" cy="${Y(pt[1])}" r="6" fill="#08796e"/><rect x="${X(v.recon[i][0])-4}" y="${Y(v.recon[i][1])-4}" width="8" height="8" fill="#b05220"/>`).join('')}<text x="20" y="365">Verde: original · naranja: reconstrucción · morado: dirección</text></svg>`;};
  s.addEventListener('input',updateMI);k.addEventListener('input',updateK);p.addEventListener('input',updateP);
  p.querySelector('button').addEventListener('click',()=>{let best=0;for(let i=1;i<=180;i++)if(projection(i).error<projection(best).error)best=i;p.querySelector('input').value=best;updateP();p.querySelector('#projection-out').insertAdjacentHTML('beforeend','<p>Dirección de máxima varianza aproximada a un grado.</p>');});updateMI();updateK();updateP();
 }
 return {mount,mi,projection};
})();
